// Introduction générale (non numérotée, développée).
module.exports = [
  { h0: `INTRODUCTION GÉNÉRALE` },

  { p: `Les liens d'accès à l'Internet à Madagascar cumulent trois propriétés rarement réunies dans les bancs d'essai publiés : un temps de propagation élevé et variable (de 50 à 600 ms selon la technologie), une capacité qui s'effondre de manière prévisible aux heures de pointe (perte de 50 à 80 % du débit nominal), et un coût par octet qui rend la mesure du gaspillage économiquement signifiante. La littérature existante mesure ces liens sans vérité terrain : on observe des symptômes (latence élevée, pertes) sans pouvoir les rattacher à des événements causes datés avec précision. Ce fossé constitue le point de départ du travail.` },

  { p: `Le phénomène central étudié est le bufferbloat, cette accumulation persistante de paquets dans des files d'attente surdimensionnées qui ajoute des centaines de millisecondes de délai sans provoquer de perte visible. Identifié et nommé au début des années 2010, le bufferbloat reste largement invisible aux métriques usuelles : le débit et le taux de perte ne le capturent pas, seule la latence sous charge le révèle. Sur un lien malgache, ses conséquences sont doubles : une dégradation de l'expérience interactive (navigation, visioconférence, voix sur IP) et un gaspillage de retransmissions qui se paie en ariary, puisque chaque octet transmis sur un forfait prépayé a été acheté. Mesurer ce phénomène avec rigueur sur cette classe de liens exige un instrument que la littérature ne fournit pas.` },

  { p: `Ce mémoire propose l'observatoire CGO (Congestion Ground-truth Observatory), un instrument de mesure expérimentale qui referme cet écart en fournissant une vérité terrain connue par construction. L'instrument repose sur une émulation contrôlée : un ordonnanceur rejoue des baisses de capacité programmées sur un lien façonné par le noyau Linux, pendant qu'un oracle extrait à 10 Hz les compteurs exacts de la file d'attente. Puisque l'instant exact de chaque baisse de capacité est imposé par l'ordonnanceur et enregistré, tout détecteur peut être évalué contre des événements datés à la milliseconde près, ce qu'aucune mesure sur lien réel ne permet. Cinq détecteurs de congestion sont confrontés à ces événements datés, et un façonneur adaptatif est comparé aux configurations statiques de gestion active de file.` },

  { p: `La démarche est organisée autour de trois questions de recherche. La première (RQ1) porte sur la détection : parmi cinq détecteurs implémentés (seuil fixe, gradient, moyenne mobile à pondération exponentielle, z-score sur médiane glissante, test de Kolmogorov-Smirnov à deux échantillons), lequel repère le plus tôt le début réel de la congestion, à coût de faux positif égal ? La deuxième (RQ2) porte sur l'estimation : avec quelle précision des sondes actives légères (paire de paquets, train de paquets) retrouvent-elles la bande passante disponible d'un lien limité en débit ? La troisième (RQ3) porte sur l'atténuation : un façonneur adaptatif déclenché par la détection fait-il mieux que des configurations statiques de gestion active de file ? Chaque question correspond à une expérience (E1, E2, E3) dont les hypothèses ont été pré-enregistrées avant l'exécution des campagnes.` },

  { p: `Trois exigences méthodologiques traversent l'ensemble du travail. La falsifiabilité d'abord : chaque hypothèse précise la direction attendue de l'effet et la condition dans laquelle il doit se manifester, de sorte qu'un résultat contraire soit interprétable comme une réfutation. La vérification croisée ensuite : chaque nombre publié est confirmé par un canal indépendant (tcpdump, iperf3, ping horodaté par le noyau), afin qu'aucune conclusion ne repose sur un seul instrument. La reproductibilité enfin : chaque figure et chaque table du mémoire sont régénérables par une commande unique à partir d'une archive de données gelée et chaînée par SHA-256, ce qui permet à tout tiers de vérifier l'intégralité des résultats.` },

  { p: `Le travail assume également un ancrage local revendiqué. Les profils de lien rejoués en émulation (RTT de 50 à 600 ms, effondrement diurne, pertes sporadiques avec gigue) sont calibrés sur des relevés effectués sur un lien 4G réel à Antananarivo, avec une carte prépayée acquise localement. Les métriques économiques convertissent les octets gaspillés en ariary par heure, ce qui rend les résultats directement interprétables par un usager ou un décideur malgache. Les contraintes opérationnelles du terrain, au premier rang desquelles les coupures électriques de la JIRAMA, sont traitées non comme des obstacles mais comme des exigences de conception : l'instrument survit aux interruptions brutales et reprend ses campagnes sans perte de données.` },

  { p: `Le mémoire s'articule en cinq parties. La première présente l'organisme d'accueil, la Direction Générale de la Météorologie (Météo Madagascar), et décrit le déroulement du stage au cours duquel ce travail a été mené. La deuxième pose le contexte malgache des liens d'accès, examine les travaux connexes et formule la problématique. La troisième applique la méthodologie d'analyse de l'existant à l'environnement de mesure, en parcourant systématiquement les onze points de la méthode. La quatrième présente l'observatoire CGO : la solution proposée, la comparaison des outils disponibles pour chaque fonction du banc, la présentation de l'outil retenu et les fondements théoriques qui le sous-tendent. La cinquième décrit le protocole expérimental et les trois campagnes E1, E2 et E3, présente les résultats obtenus, les discute et en précise les limites. Une conclusion générale, les références, un glossaire et les annexes complètent le document.` },

  { p: `Avant d'aborder le contenu technique, la première partie présente l'organisme au sein duquel ce travail a été réalisé, la Direction Générale de la Météorologie, et les conditions dans lesquelles le stage s'est déroulé.` },
];
