// 01-intro — Introduction générale (2-3 p.).
module.exports = [
  { h0: 'INTRODUCTION GÉNÉRALE' },
  { p: 'Météo Madagascar conduit chaque jour une mission dont dépendent l\'aviation, l\'agriculture et la protection civile : observer le temps, produire des prévisions, diffuser des alertes. Cette mission s\'appuie sur des applications qui se partagent des liens d\'accès très inégaux. Au siège d\'Antananarivo, une connexion en fibre optique assure un débit confortable. Dans les directions régionales, le trafic emprunte la 4G de l\'opérateur Yas. Dans les stations isolées, le satellite géostationnaire reste parfois la seule option, avec six cents millisecondes d\'aller-retour. À ces inégalités techniques s\'ajoute une contrainte économique qui n\'apparaît dans aucun banc d\'essai publié : la connexion mobile se vend par forfaits prépayés, où 25 000 ariary achètent 4,5 gigaoctets pour un mois. Chaque octet retransmis à cause de la congestion est un octet payé deux fois.' },
  { p: 'Ces liens transportent deux familles de trafic qui se disputent la même capacité. D\'un côté, un trafic de masse : images satellite, modèles numériques, sauvegardes, dont le volume se compte en gigaoctets et qui tolère l\'attente. De l\'autre, un petit trafic critique : relevés des stations automatiques, consultations de tableaux de bord, alertes, dont le temps de réponse décide de l\'utilité opérationnelle. Lorsqu\'un transfert massif occupe le lien, les paquets des petites requêtes s\'accumulent dans les files d\'attente des équipements. Le débit ne baisse pas forcément ; c\'est le temps de réponse qui se dégrade, parfois jusqu\'à rendre le service inutilisable. Ce phénomène porte un nom, le bufferbloat, et il a été documenté dès 2011 par Gettys et Nichols comme l\'une des causes majeures de dégradation perçue sur Internet.' },
  { p: 'Les remèdes connus sont de deux ordres. Du côté des équipements, les disciplines de file actives, comme fq_codel et CAKE, régulent la longueur des files au lieu de les laisser croître. Du côté des émetteurs, l\'algorithme de contrôle de congestion détermine le rythme d\'émission : CUBIC, fondé sur la perte, remplit les files avant de ralentir ; BBR, proposé par Google en 2016, estime la capacité et le délai minimal pour éviter de remplir les files. La question n\'est pas de savoir si ces mécanismes fonctionnent : leur efficacité est établie. Elle est de savoir lesquels servent le mieux un contexte donné : des liens cellulaires et satellitaires, prépayés, transportant à la fois de la télémétrie et des téléchargements massifs, dans un pays où chaque gigaoctet a un prix.' },
  { p: 'La direction des systèmes d\'information de Météo Madagascar devait jusqu\'ici prendre ces décisions sans données locales. Les outils publics de mesure, tels que Flent ou iperf3, s\'exécutent sur des liens réels dont l\'état exact n\'est pas contrôlé ; ils observent des symptômes sans permettre la comparaison reproductible de configurations. Ce mémoire comble ce manque par une démarche en deux volets. Le premier volet définit une méthode d\'audit non intrusif des liens accessibles depuis un poste client, sans modification des équipements de production. Le second volet installe un banc d\'essai reproductible sur ce même poste : une paire de liens virtuels reconstitue le lien d\'accès avec son délai, sa gigue et sa perte, une discipline de file testée y est appliquée, et un protocole fixe compare les combinaisons de discipline de file et de contrôle de congestion. Chaque événement de mesure franchit huit portes de qualité avant d\'être gelé dans un fichier archivé avec son empreinte SHA-256 ; toute figure du mémoire se régénère depuis ces fichiers et non depuis des valeurs saisies à la main.' },
  { p: 'La mesure produit alors une réponse au problème posé. Sur le profil cellulaire retenu, quand un transfert massif sature le lien, la file simple laisse 60 % des petites requêtes arriver sous une échéance de 220 millisecondes ; les disciplines actives en sauvent 96 à 98 pour cent, en préservant le débit. L\'écart entre latence de queue et latence médiane, qui mesure la régularité du lien, tombe de 57 ms à environ 13 ms. Appliqué aux tarifs réels de 2026, le gaspillage observé se chiffre en centaines d\'ariary par heure de charge sur un lien cellulaire, et dix fois moins sur la fibre. Ces résultats fondent une recommandation opérationnelle pour les équipements sous le contrôle de la direction des systèmes d\'information.' },
  { p: 'Le mémoire s\'organise en trois parties. La première justifie le sujet : l\'institution d\'accueil, le contexte malgache des liens d\'accès, la problématique et les objectifs. La deuxième partie expose le cadre théorique : la méthodologie d\'audit et d\'expérimentation, les équations des mesures, le protocole des campagnes et les matériels employés. La troisième partie décrit la réalisation pratique, présente les résultats mesurés et les interprète jusqu\'aux recommandations opérationnelles. La conclusion générale répond aux questions de recherche et ouvre les perspectives.' },
];
