// Partie II : Contexte et état de l'art.
// Blocks : h1 (Partie), h2 (section 1.x), h3 (1.x.y), p, fig {id, file, caption}, table {id, caption, header, rows, widths?, align?}.
// Cross-refs inline : «{figRef:ID}» et «{tabRef:ID}» sont remplacés par des champs REF dans le builder.
module.exports = [
  { h1: `PARTIE II : CONTEXTE ET ÉTAT DE L'ART` },

  { p: `Cette partie situe le travail dans son environnement. Elle décrit d'abord les liens d'accès malgaches sous quatre angles : l'infrastructure de connectivité, le coût rapporté au pouvoir d'achat, les contraintes opérationnelles qui pèsent sur toute instrumentation, et le cadre réglementaire applicable. Elle examine ensuite les travaux connexes en trois volets : la mesure du bufferbloat, l'adaptation de débit et la reproductibilité des mesures. Elle formule enfin la problématique sous la forme de trois questions de recherche, chacune assortie d'une hypothèse falsifiable.` },

  // ================================================================ 1. Contexte malgache
  { h2: `Le contexte malgache des liens d'accès` },

  { h3: `Infrastructure de connectivité` },
  { p: `Madagascar compte 6,71 millions d'internautes en octobre 2025 [1] pour une population d'environ 30 millions d'habitants. Le taux de pénétration est parmi les plus faibles du monde : 20,37 % de la population utilisait Internet en 2023 selon la Banque Mondiale [2]. Ce chiffre place le pays dans le groupe des économies numériquement les moins connectées de la planète, aux côtés de l'Érythrée et de la République démocratique du Congo. Le pays dénombre 18,2 millions de connexions mobiles [3] : l'accès passe quasi exclusivement par le terminal mobile. La téléphonie fixe, historiquement portée par des lignes cuivre dégradées et un réseau DSL quasi inexistant, ne pèse plus dans la connectivité numérique nationale.` },
  { p: `La couverture 4G n'atteignait que 34,6 % de la population en 2024, contre une moyenne africaine de 75,2 % [5]. Ce retard est plus marqué en zone rurale, qui concentre plus de 60 % de la population malgache. Quatre opérateurs mobiles (Telma, Orange, Airtel et Yas) se partagent le marché sous la régulation de l'ARTEC [20]. Chacun détient une licence d'exploitation attribuée par l'État et doit satisfaire à des obligations de couverture progressives, suivies par l'observatoire des infrastructures [22]. La répartition des fréquences et les bandes attribuées (700 MHz, 1800 MHz, 2600 MHz) influent directement sur la portée des cellules et la qualité de la réception à l'intérieur des bâtiments, ce qui a des conséquences sur les profils de perte et de gigue observés dans les campagnes de mesure.` },
  { p: `La capacité internationale a été renforcée ces dernières années par deux câbles sous-marins, dont la {figRef:cables} présente le positionnement. Le câble METISS, en service depuis mars 2021 [8], long de 3 200 kilomètres, relie Maurice, La Réunion, Madagascar et l'Afrique du Sud [6][7]. Sa capacité atteint 12 Tbit/s. Le câble 2Africa, atterri à Mahajanga par le partenariat Telma-Vodafone [9][10], ajoute une capacité supplémentaire de 180 Tbit/s à l'échelle du système. La contrainte ne se situe donc plus sur le segment international : elle est au dernier kilomètre radio.` },
  { fig: { id: 'cables', file: 'fig01-cables', caption: `Positionnement des câbles sous-marins METISS et 2Africa autour de Madagascar (schéma simplifié).` } },
  { p: `La capacité partagée d'une cellule 4G s'effondre aux heures de pointe. Les réseaux d'accès des abonnés, dimensionnés pour un trafic moyen, n'absorbent pas les pics de soirée. Hors des villes, le VSAT reste souvent la seule option, avec des RTT de l'ordre de 600 ms. Le pays se classe 136ème mondial pour le débit fixe [4]. Les débits mobiles réels mesurés sont souvent inférieurs aux débits annoncés par les opérateurs, et l'écart entre le débit théorique et le débit pratique pendant les heures chargées peut atteindre 70 %. Cette dégradation cyclique, prévisible mais difficile à anticiper pour le protocole de transport, est une caractéristique centrale de la classe de liens étudiée.` },
  { p: `Starlink a introduit une alternative satellitaire en orbite basse. Le matériel coûte 1 120 000 MGA et l'abonnement résidentiel 226 000 MGA par mois [12], avec un forfait Résidentiel Lite à 136 000 MGA [13]. Les frais d'activation atteignent 1 140 000 MGA [14] et le kit standard motorisé 1 580 000 Ar [15]. Le kit mini dish est à 900 000 Ar. La connectivité performante reste un bien coûteux. Dans un environnement où le coût unitaire de la donnée est élevé, chaque octet retransmis coûte de l'argent. Pour un ménage au revenu mensuel médian de 200 000 MGA, un abonnement Starlink à 136 000 MGA représente les deux tiers du budget, ce qui le place hors de portée pour la majorité de la population.` },
  { table: {
      id: 'liens',
      caption: `Synthèse des liens d'accès disponibles à Madagascar.`,
      header: ['Lien', 'Débit typique', 'RTT typique', 'Coût mensuel (MGA)', 'Couverture', 'Source'],
      rows: [
        ['4G prépayé', '5 à 20 Mbit/s', '50 à 150 ms', '30 000 (1 à 2 Go)', '34,6 % pop.', '[1][3][5]'],
        ['VSAT', '1 à 10 Mbit/s', '600 ms', 'Variable', 'Zones non couvertes', '[4]'],
        ['Fibre opérateur', '50 à 200 Mbit/s', '< 20 ms', 'Contrat entreprise', 'Villes principales', '[20][21]'],
        ['Starlink LEO', '50 à 220 Mbit/s', '25 à 50 ms', '136 000 à 226 000', 'National', '[12] à [15]'],
      ],
      widths: [16, 17, 15, 21, 18, 13],
  } },
  { p: `Le {tabRef:liens} résume les quatre catégories de liens. Chaque technologie occupe un segment différent du compromis coût-débit-latence-couverture. La 4G prépayée est la plus accessible géographiquement et financièrement, mais elle souffre d'une variabilité de débit et d'une latence qui se dégrade avec l'encombrement. Le VSAT couvre les zones blanches au prix d'une latence très élevée. La fibre concerne les entreprises et les institutions dans les grandes villes. Starlink offre le meilleur compromis débit-latence mais à un coût d'entrée dissuasif pour un usage individuel.` },
  { p: `Cette cartographie a une conséquence directe sur la conception du dispositif expérimental. La classe de liens à caractériser en priorité est le lien 4G prépayé, parce qu'il concentre la majorité des usages réels et cumule les trois propriétés qui motivent le travail : latence variable, capacité qui s'effondre et coût par octet élevé. Le profil VSAT est retenu comme cas limite de propagation (600 ms), et la fibre comme référence de lien peu contraint. Ces trois profils structurent la matrice expérimentale présentée dans la cinquième partie.` },

  { h3: `Coût et pouvoir d'achat` },
  { p: `Un lien de « classe malgache » est un lien hautement asymétrique en coût : la latence ajoutée par la congestion se traduit en argent (retransmissions, octets gaspillés, temps d'attente) pour un usager dont le budget de données est limité. Cela le distingue des pays où l'accès est forfaitaire illimité. Le projet prend cette dimension économique en compte dans les métriques, avec les octets gaspillés comme indicateur secondaire. Cette métrique relie directement la performance technique à l'impact financier pour l'usager, ce qui est rare dans la littérature sur la congestion où le coût du gaspillage est rarement quantifié.` },
  { p: `L'ordre de grandeur mérite d'être posé. Un forfait prépayé courant coûte environ 30 000 MGA pour un à deux gigaoctets, soit un coût unitaire de 15 000 à 30 000 MGA par gigaoctet. Un flux TCP qui subit un épisode de bufferbloat sévère peut retransmettre plusieurs dizaines de kilooctets par événement de congestion ; répété sur des dizaines d'événements quotidiens aux heures de pointe, ce gaspillage se chiffre en centaines de mégaoctets par mois, soit une fraction tangible du forfait. La cinquième partie convertit systématiquement les octets gaspillés mesurés en ariary par heure, ce qui rend le résultat directement interprétable par un usager ou un décideur local.` },
  { p: `Cette contrainte économique modifie les hypothèses de conception par rapport aux travaux menés dans des pays où l'accès est forfaitaire et illimité. Dans ces contextes, une retransmission supplémentaire ne coûte rien à l'usager ; à Madagascar, elle consomme un volume qui a été payé. La métrique d'octets gaspillés devient ainsi un indicateur économique direct. Les résultats des expériences seront interprétés non seulement en termes de performance réseau, mais aussi en termes de coût évité pour l'usager.` },

  { h3: `Contraintes opérationnelles` },
  { p: `Deux contraintes pèsent sur toute instrumentation. La première est énergétique. La JIRAMA publie des prévisions de coupures [16]. L'année 2025 a vu une intensification du délestage à Antananarivo [18], aggravée par la sécheresse qui a réduit la production du barrage d'Andekaleka [17]. La Banque Mondiale alerte sur un risque accru en 2025 et 2026 [19]. Les coupures durent de quelques heures à une journée et surviennent sans préavis fiable.` },
  { p: `Un dispositif de mesure déployé dans ces conditions doit survivre à des interruptions brutales sans perdre les données en cours. Cela implique une architecture avec détection de coupure, sauvegarde d'état et reprise automatique. L'alimentation par batterie ou onduleur peut couvrir des coupures courtes, mais une stratégie de point de reprise (checkpoint) est nécessaire pour les coupures longues. Les données collectées avant l'interruption ne doivent pas être perdues, ce qui impose un mécanisme d'écriture atomique et de vérification d'intégrité au redémarrage.` },
  { p: `La seconde contrainte est la variabilité radio. La liaison 4G présente une variation diurne marquée : la capacité mesurée en journée diffère de celle observée en soirée. La gigue et les pertes sporadiques sont la norme. Cette variabilité n'est pas un artefact de mesure : c'est une propriété du canal hertzien partagé, influencée par la distance à l'antenne, la météo, le nombre d'usagers et les interférences. Ces deux contraintes définissent les profils expérimentaux (effondrement diurne, contexte avec pertes et gigue) et les exigences de robustesse (hors ligne, reprise, écriture atomique) que l'instrument devra satisfaire.` },

  { h3: `Cadre réglementaire` },
  { p: `L'ARTEC régule les télécommunications et les TIC à Madagascar [20]. Elle octroie les licences, reçoit les déclarations des opérateurs et délivre les agréments [28]. Elle publie un observatoire du marché [21] et un observatoire des infrastructures [22]. Elle participe au réseau FRATEL, dans le cadre duquel elle a répondu à un questionnaire sur la couverture et la qualité de service mobile [23]. Le rôle de l'ARTEC est central dans le suivi des obligations de couverture des opérateurs, même si les données publiées n'offrent pas une granularité suffisante pour évaluer la qualité de service perçue par l'usager.` },
  { p: `Deux points réglementaires concernent le projet. Les équipements terminaux doivent être homologués avant commercialisation. L'ARTEC publie la liste des matériels agréés [24], et l'homologation RF est obligatoire [25]. Dans le projet, le modem 4G est acquis localement auprès d'un distributeur agréé, ou remplacé par le partage de connexion d'un téléphone déjà homologué. La loi n° 2014-038 sur la protection des données [26][27] est respectée par construction : les captures portent sur du trafic synthétique, sans données d'usagers tiers. L'activité étant académique et passive, elle ne relève ni d'une étude d'impact environnemental auprès de l'ONE, ni d'un enregistrement d'investissement à l'EDBM. Le protocole expérimental respecte donc l'ensemble des exigences légales applicables sans nécessiter d'autorisation supplémentaire.` },

  // ================================================================ 2. Travaux connexes
  { h2: `Travaux connexes` },

  { p: `L'état de l'art pertinent pour ce travail se répartit en trois champs : la mesure du bufferbloat, qui fournit les instruments et les métriques de référence ; l'adaptation de débit, qui fournit les comparateurs opérationnels du bras adaptatif ; et la culture de reproductibilité des conférences de mesure, qui fournit les exigences méthodologiques. Chaque champ est examiné pour ce qu'il apporte et pour la lacune qu'il laisse ouverte.` },

  { h3: `Mesure du bufferbloat` },
  { p: `Le bufferbloat a été identifié et nommé par Gettys et Nichols [34] : des files d'attente surdimensionnées, placées dans les équipements d'accès, accumulent des paquets pendant les périodes de charge et ajoutent des centaines de millisecondes de délai sans produire de perte. Le phénomène est resté longtemps invisible parce que les métriques usuelles (débit, taux de perte) ne le capturent pas : seule la mesure de la latence sous charge le révèle. La réponse algorithmique est venue de Nichols et Jacobson avec CoDel [33][31], puis de sa variante à répartition par flux fq_codel [30], standardisées par l'IETF [32].` },
  { p: `La mesure du bufferbloat s'est structurée autour d'outils composables. Flent, développé par Høiland-Jørgensen [43][44], orchestre plusieurs instances de netperf, iperf et ping et agrège les résultats en séries reproductibles. Il permet des tests combinés (flux TCP de fond avec sondes ping, ou flux UDP avec mesure de pertes) et produit des graphiques de débit et de latence au cours du temps. Flent a été utilisé dans les études fondatrices sur l'impact du bufferbloat sur la navigation web et le streaming vidéo.` },
  { p: `Flent standardise la procédure de test et réduit la variabilité liée à l'orchestration manuelle. Il a été utilisé dans de nombreuses études sur le bufferbloat et la comparaison d'algorithmes AQM. Les études de Høiland-Jørgensen et al. sur CAKE et fq_codel [38] ont démontré l'efficacité des disciplines de file modernes pour réduire la latence de file. Mais les instruments comme Flent mesurent des liens réels dont la vérité terrain (instant exact de début de congestion, capacité à chaque instant) est inconnue : ils observent des symptômes, pas des événements datés. C'est la limite que ce travail cherche à combler en fournissant une vérité terrain contrôlée.` },
  { p: `Dans la littérature récente, plusieurs travaux ont cherché à caractériser le bufferbloat sur des liens mobiles. Les études mesurant le RTT sur des réseaux 4G dans différentes régions du monde montrent que le phénomène est particulièrement prononcé sur les liaisons asymétriques et dans les zones où la capacité radio est partagée entre de nombreux usagers. Ces travaux confirment que le bufferbloat n'est pas un artefact de laboratoire mais une propriété récurrente des réseaux d'accès mobiles. Cependant, aucun de ces travaux ne dispose d'une vérité terrain qui permette d'isoler la contribution de la congestion de celle des autres sources de variation du RTT.` },
  { fig: { id: 'rttphases', file: 'fig02-rtt-phases', caption: `Décomposition du RTT sur un lien contraint : phases normale, de bufferbloat et de récupération.` } },
  { p: `La {figRef:rttphases} illustre le phénomène que les détecteurs devront capter : un lien au repos présente un RTT stable proche du délai de propagation ; lorsque la charge sature le goulot, la file se constitue et le RTT s'élève de plusieurs centaines de millisecondes ; lorsque la charge cesse ou que la gestion active de file intervient, le RTT redescend en quelques secondes. La détection précoce consiste à repérer la transition entre la première et la deuxième phase le plus tôt possible, avant que la file ne soit pleinement constituée.` },

  { h3: `Adaptation de débit et réglage adaptatif` },
  { p: `Les projets d'adaptation automatique de débit ajustent la capacité façonnée à partir de la latence observée. Smart Queue Management (SQM) dans OpenWrt ou les scripts d'ajustement dynamique modifient les paramètres de façonnage en fonction des conditions. Le principe est le suivant : si la latence dépasse un seuil, le débit est réduit ; si elle revient à un niveau acceptable, il est augmenté. D'autres approches, comme le contrôle adaptatif de bande passante proposé dans certains travaux sur les réseaux longue distance, utilisent une boucle de rétroaction proportionnelle-intégrale (PI) pour ajuster le débit de façon continue.` },
  { p: `Ces outils sont des comparateurs opérationnels pour le bras adaptatif de E3. Mais leur évaluation repose sur l'observation en production, sans oracle. On valide par la diminution de latence, sans savoir si la réduction de débit était nécessaire ou excessive, puisque la capacité réelle est inconnue. Ce travail se situe en amont : il fournit la vérité terrain qui manque à ces évaluations, en contrôlant exactement la capacité et le trafic traversant dans un environnement émulé. Les résultats de E3 permettront de calibrer ces approches adaptatives avec une référence objective.` },

  { h3: `Reproductibilité et accord entre mesures` },
  { p: `La culture de mesure (conférences PAM, IMC, TMA) impose des exigences standard : hypothèses pré-enregistrées, données archivées avec DOI, code de régénération des figures. Ces pratiques, inspirées de la crise de la réplication en psychologie, garantissent que les résultats sont vérifiables et que les conclusions ne dépendent pas de choix arbitraires dans le traitement. Le présent travail s'inscrit dans cette démarche : les scénarios de test, les paramètres de l'émulateur et le code d'analyse sont publiés avec un identifiant pérenne.` },
  { p: `La validation des canaux de mesure utilise la méthode de Bland et Altman [45], développée pour la recherche clinique. Le graphique de Bland-Altman porte les différences entre deux mesures en ordonnée contre leurs moyennes en abscisse, avec les limites d'accord (moyenne des différences plus ou moins 1,96 écart-type). Ce cadre quantifie la concordance entre l'oracle et les instruments tiers (Flent, iperf3) et vérifie que les biais éventuels sont acceptables au regard des objectifs de l'étude. L'application de cette méthode à la validation d'instruments de mesure réseau est relativement récente et rare dans la littérature sur la congestion, où la validation se limite souvent à une comparaison visuelle des séries temporelles.` },
  { p: `Trois lacunes ressortent de cet examen. Les instruments de mesure du bufferbloat observent des symptômes sans vérité terrain ; les systèmes adaptatifs sont évalués sans référence objective de capacité ; et la validation croisée quantitative entre canaux de mesure reste l'exception. L'instrument proposé dans ce mémoire répond simultanément aux trois : il date les événements par construction, il connaît la capacité imposée à chaque instant, et il réconcilie systématiquement ses mesures avec des instruments tiers.` },

  // ================================================================ 3. Problématique
  { h2: `Problématique et motivation` },

  { p: `Les liens d'accès malgaches cumulent trois propriétés rarement réunies dans la littérature : un RTT élevé et variable (50 à 600 ms), une capacité qui s'effondre aux heures de pointe (perte de 50 à 80 %), et un coût par octet qui rend le gaspillage économiquement signifiant. Les études existantes mesurent ces liens sans vérité terrain : elles observent des symptômes sans pouvoir les rattacher à des événements datés. Les études d'émulation les modélisent sans les ancrer dans des profils réels. Ce double fossé est le point de départ du travail.` },
  { p: `Trois questions de recherche en découlent, chacune correspondant à une expérience du protocole. RQ1 (détection, expérience E1) : sur un lien contraint en émulation contrôlée, quel détecteur repère le plus tôt le début réel de la congestion, à coût de faux positif égal ? Les cinq détecteurs sont comparés sur des scénarios dont le début est connu par construction grâce à l'oracle. La question porte sur le compromis précocité-fausses alarmes dans un environnement où le RTT de base est variable. L'hypothèse H1 est que le test K-S détecte la congestion significativement plus tôt que les méthodes à seuil fixe et à gradient, en particulier dans les scénarios de rampe progressive.` },
  { p: `RQ2 (estimation, expérience E2) : avec quelle précision des sondes légères (paire de paquets, train de paquets) retrouvent-elles la bande passante disponible réelle d'un lien limité en débit, en fonction de l'intensité du trafic traversant ? La réponse fournit une courbe de calibration pour E3 et quantifie le biais et la variance de chaque sonde. L'hypothèse H2 est que la précision de l'estimation décroît avec le taux d'occupation du lien, et que la dispersion de paires surpasse le train de paquets aux faibles taux d'occupation.` },
  { p: `RQ3 (atténuation, expérience E3) : un façonneur adaptatif déclenché par la détection fait-il mieux que des configurations statiques d'AQM en matière de dégradation de latence, temps de récupération et gaspillage de retransmission ? Le réglage par défaut (fq_codel) est la référence pratique. La question sous-jacente est de savoir s'il suffit déjà ou si une couche adaptative apporte un gain mesurable. La comparaison porte sur QDI, TTB, p95 de latence et indicateur VoIP. L'hypothèse H3 est que l'approche adaptative réduit à la fois le délai de file et les octets gaspillés par rapport aux configurations statiques, mais au prix d'une légère réduction du débit utile.` },
  { table: {
      id: 'rq',
      caption: `Correspondance entre questions de recherche, expériences et hypothèses.`,
      header: ['Question', 'Objet', 'Expérience', 'Hypothèse pré-enregistrée'],
      rows: [
        ['RQ1', 'Détection précoce des événements de congestion', 'E1 (204 onsets)', 'H1 : le test K-S détecte plus tôt que le seuil fixe et le gradient, surtout sur les rampes'],
        ['RQ2', 'Précision des sondes actives d\u2019estimation', 'E2 (concordance)', 'H2 : la précision décroît avec l\u2019occupation ; la paire de paquets domine à faible charge'],
        ['RQ3', 'Gain du façonneur adaptatif face aux AQM statiques', 'E3 (152 événements)', 'H3 : l\u2019adaptatif réduit délai de file et gaspillage, au prix d\u2019un léger débit utile'],
      ],
      widths: [10, 28, 18, 44],
  } },
  { p: `Le {tabRef:rq} met en regard les trois questions, les trois expériences et les trois hypothèses. Chaque hypothèse est formulée de manière falsifiable : elle précise la direction attendue de l'effet et la condition dans laquelle il doit se manifester, de sorte qu'un résultat contraire soit interprétable comme une réfutation et non comme un échec de la mesure.` },
  { p: `La motivation est triple. Scientifique : établir, sur une classe de liens sous-étudiée, des faits falsifiables plutôt que des observations symptomatiques. Les liens malgaches ne sont pas un cas exotique : ils représentent les conditions d'accès de plusieurs milliards d'utilisateurs dans le monde, dans les pays où la connectivité mobile est le mode d'accès principal et où le coût de la donnée représente une part significative du revenu. Méthodologique : fournir un protocole d'audit à vérité terrain, transférable à d'autres institutions. Le dispositif est conçu pour être reproductible (matériel spécifié, logiciels conteneurisés, procédures documentées, données archivées). Locale : doter l'écosystème malgache d'un outil pour confronter les déclarations de qualité de service des opérateurs à des mesures indépendantes. Dans un marché où l'information est asymétrique, un outil de mesure ouvert peut servir la transparence et servir de support pédagogique dans les universités.` },
  { p: `Ces trois dimensions sont liées : la rigueur scientifique garantit la crédibilité des résultats, la démarche méthodologique assure leur transférabilité, et l'ancrage local donne au travail une utilité concrète au-delà de la publication académique. Chacune des trois questions de recherche est conçue pour produire des réponses qui servent à la fois la communauté scientifique et les acteurs locaux : un opérateur peut utiliser la méthode de détection pour diagnostiquer ses liens, un régulateur peut s'appuyer sur les résultats d'estimation pour évaluer la qualité de service déclarée, un étudiant peut reproduire les expériences dans le cadre de sa formation.` },
  { p: `Les contributions attendues sont de trois ordres. Un jeu de données de validation contenant les séries temporelles de débit et de latence avec vérité terrain, pour les trois expériences. Une comparaison systématique des cinq détecteurs sur des profils de lien inspirés des conditions malgaches, avec une métrique de précocité conditionnelle au taux de faux positifs. Une évaluation du gain apporté par un façonneur adaptatif par rapport aux réglages statiques, avec une attention particulière au gaspillage de retransmission comme indicateur économique.` },
  { p: `Ces trois questions appellent une méthode capable de produire des réponses falsifiables : c'est l'objet de la partie suivante, qui applique l'analyse de l'existant à l'environnement de mesure et fonde le choix de la solution.` },
];
