// 02-partie1 — suite Partie I : contexte des liens, problématique, objectifs.
module.exports = [
  { h2: 'Les liens d\'accès malgaches' },
  { h3: 'Les quatre classes de liens' },
  { p: 'Quatre classes de liens d\'accès structurent la connectivité institutionnelle malgache. La fibre optique, présente dans les environnements institutionnels et urbains, offre des capacités de plusieurs dizaines de mégabits par seconde avec un aller-retour de l\'ordre de 20 ms. Les réseaux mobiles 4G et 5G, opérés principalement par Yas (l\'ancien Telma), Airtel et Orange, desservent la majorité des sites avec des capacités variables selon la charge de la cellule et des délais de l\'ordre de 100 ms. Le satellite géostationnaire, ou VSAT, dessert les sites hors de portée des autres technologies : il ajoute un délai de propagation d\'environ 600 ms, imposé par la distance jusqu\'à l\'orbite géostationnaire, pour une capacité faible. Enfin Starlink, arrivé sur le marché malgache en 2024, propose une liaison par satellite en orbite basse avec un délai d\'environ 40 ms et un débit élevé, pour un abonnement mensuel rapporté à 226 000 ariary par la presse de 2025.' },
  { p: 'La classe fibre sert de référence à toutes les autres, et c\'est pourquoi elle est détaillée ici. Pour le grand public, l\'offre FTTH de l\'opérateur principal commence à 49 000 ariary par mois pour 100 gigaoctets, et l\'opérateur Orange propose une offre comparable depuis la fin 2024. Pour les institutions, l\'étage supérieur se compose de liaisons dédiées : les grilles publiées par l\'opérateur principal font apparaître une liaison GOLD à 1 000 000 d\'ariary par mois pour jusqu\'à 200 mégabits par seconde, et des liaisons PLATINE jusqu\'à 4 000 000 d\'ariary sans plafond de volume. Le fossé entre le FTTH grand public et la liaison dédiée institutionnelle couvre un facteur quarante : la position d\'un site dans cette échelle détermine sa marge de manœuvre face à la congestion.' },
  { p: 'La classe cellulaire est la plus répandue et la plus hétérogène. La 4G couvre les chefs-lieux de région et une partie des axes principaux ; la 5G, déployée depuis 2020 par l\'opérateur principal, reste confinée au centre d\'Antananarivo. La capacité réelle d\'une cellule varie avec le nombre d\'abonnés actifs : le même site régional peut offrir vingt mégabits par seconde aux heures creuses et une fraction de cette valeur au soir. Cette variabilité temporelle est précisément ce que le banc reproduit par ses profils : le profil cellulaire retenu correspond à une cellule chargée, le cas dégradé que la direction des systèmes doit affronter.' },
  { p: 'Le VSAT géostationnaire obéit à la physique et non au marché : à 36 000 kilomètres d\'altitude, l\'aller-retour impose environ 600 millisecondes avant tout traitement. Aucune configuration locale ne réduira cette constante. La discipline de file active conserve pourtant son utilité sur ces liens : les études menées sur le bufferbloat satellite montrent que la taille des files d\'attente s\'y accumule d\'autant plus vite que le produit délai × capacité est élevé. Le mémoire mesure ce cas à travers le profil P3, avec une lecture honnête des archives : aucune cellule valide n\'y a été gelée, ce que la partie pratique documente.' },
  { p: 'Starlink, dernière arrivée, change l\'ordre de grandeur du satellite : l\'orbite basse ramène l\'aller-retour vers 40 millisecondes, la capacité vers le centaine de mégabits, au prix d\'une gigue propre aux relais entre satellites et d\'un abonnement de 226 000 ariary par mois au plancher rapporté en 2025, auquel s\'ajoutent le kit à 900 000 ariary et les frais d\'activation à 1 140 000 ariary. Pour une institution répartie sur un territoire aussi vaste que Madagascar, cette offre ouvre une alternative crédible aux directions régionales isolées, et le profil P4 en mesure la classe de latence et de gigue.' },
  { p: 'Toute recommandation de configuration qui ignorerait cette hétérogénéité serait vouée à l\'échec sur une partie du parc : c\'est la raison d\'être des profils de banc définis dans la partie théorique. Ces quatre classes se traduisent en quatre profils, notés P1 à P4, dont le {tabRef:profils} récapitule les paramètres. Ces valeurs sont représentatives des classes de liens plutôt que des mesures d\'un site précis ; la calibration depuis un audit de terrain reste un prolongement.' },
  { table: { id: 'profils', caption: 'Profils de liens utilisés dans le banc d\'essai', header: ['Profil', 'Classe de lien', 'Capacité', 'Délai (RTT)', 'Gigue', 'Perte'],
    widths: [12, 30, 14, 14, 14, 28],
    rows: [
      ['P1', 'Fibre', '80 Mbit/s', '20 ms', '2 ms', '0 %'],
      ['P2', '4G/5G cellulaire', '20 Mbit/s', '100 ms', '15 ms', '0,5 %'],
      ['P3', 'VSAT géostationnaire', '5 Mbit/s', '600 ms', '30 ms', '1 %'],
      ['P4', 'Starlink (orbite basse)', '100 Mbit/s', '40 ms', '20 ms', '0,3 %'],
    ] } },
  { p: 'Le profil P2 concentre l\'étude : il correspond au cas d\'usage le plus fréquent hors du siège, un lien cellulaire partagé entre trafic de consultation et transferts. Les trois autres profils servent de bornes : un lien stable en référence, un lien très contraint, et l\'alternative satellite récente.' },

  { h3: 'Les câbles sous-marins et la fragilité internationale' },
  { p: 'Cette hiérarchie locale s\'appuie sur un socle international : les câbles sous-marins. Madagascar est desservie par plusieurs systèmes dont deux structurent le marché : METISS, mis en service en 2021, relie l\'Afrique du Sud à Toamasina puis La Réunion et Maurice sur 3 200 kilomètres pour 12 térabits par seconde ; 2Africa, l\'un des plus grands systèmes au monde avec 180 térabits par seconde à l\'échelle du réseau, atterrit à Mahajanga. Chaque addition de capacité internationale fait baisser le prix du gigaoctet transporté, et les atterrissements successifs ont accompagné la baisse des tarifs de détail observée sur la décennie.' },
  { fig: { id: 'figCables', file: 'fig01-cables', caption: 'Atterrissements de câbles sous-marins de Madagascar : METISS à Toamasina, 2Africa à Mahajanga' } },
  { p: 'Ce socle reste fragile. La coupure d\'un câble sous-marin dégrade instantanément la capacité internationale disponible, et les incidents de ce type survenus dans la région de l\'océan Indien ces dernières années ont montré la dépendance du pays à un petit nombre d\'atterrissements. La leçon pour ce mémoire est double. D\'une part, la contrainte de capacité se joue au dernier kilomètre, radio ou cellulaire, bien plus souvent qu\'au niveau international : c\'est le goulet d\'étranglement que le banc reconstitue. D\'autre part, la redondance des accès, fibre et satellite, fait partie du quotidien des réseaux institutionnels malgaches, ce qui justifie que l\'instrument couvre les quatre classes plutôt que de se spécialiser.' },

  { h3: 'La contrainte économique : la donnée prépayée' },
  { p: 'La spécificité malgache la plus déterminante pour ce travail est le modèle de tarification. La connexion y est le plus souvent vendue par paquets prépayés : un volume, une durée, un prix. Chez l\'opérateur principal, 25 000 ariary achètent 4,5 gigaoctets pour trente jours, soit un prix du gigaoctet cinq fois supérieur à celui du forfait de 100 gigaoctets du même opérateur. Le quotidien le plus petit, un gigaoctet pour 24 heures à 1 000 ariary, offre paradoxalement le meilleur rapport au gigaoctet du catalogue. La fibre fixe commence à 49 000 ariary pour 100 gigaoctets mensuels, soit environ dix fois moins cher au gigaoctet que le forfait cellulaire de référence.' },
  { fig: { id: 'figTarifsCtx', file: 'figR4-tarifs', caption: 'Prix du gigaoctet selon le forfait, opérateur principal, 2026' } },
  { p: 'La comparaison des trois opérateurs complète le tableau. Airtel aligne son forfait mensuel de 4,5 gigaoctets à 25 000 ariary, identique à l\'opérateur principal, et propose un bonus de vingt pour cent pour l\'achat via le portefeuille mobile. Orange vise plutôt les petits volumes avec sa gamme Akama et les forfaits Be Connect hebdomadaires. Le marché converge donc sur le palier mensuel de référence, ce qui simplifie le calcul de coût du mémoire sans l\'y enfermer : le palier reste un paramètre, et l\'écart des prix au gigaoctet entre forfaits d\'un même opérateur dépasse le facteur cinq.' },
  { p: 'Le renversement touche le budget institutionnel directement, et il faut s\'y arrêter. Le forfait journalier d\'un gigaoctet à 1 000 ariary présente le meilleur rapport du catalogue mobile ; le mensuel de 4,5 gigaoctets à 25 000 ariary présente le pire à 5 556 ariary par gigaoctet. Un site régional consommant quelques dizaines de gigaoctets par mois paie des centaines de milliers d\'ariary s\'il s\'approvisionne au palier de référence : d\'où l\'intérêt de mesurer avant de dépenser, et de chiffrer le gaspillage au palier réellement souscrit. La presse économique de novembre 2025 situe le prix moyen du gigaoctet malgache à 0,32 dollar selon une source et 1,12 dollar selon l\'étude comparative internationale qui place le pays au rang 106 sur 237 : ces ordres de grandeur confirment un marché intérieur cher au regard des moyennes régionales.' },
  { p: 'Cette structure de prix donne un sens économique direct à chaque paquet retransmis inutilement. En octobre 2025, l\'autorité de régulation a convoqué les opérateurs à la suite d\'une vague de plaintes publiques sur le coût de la donnée ; le débat public porte précisément sur la valeur d\'un mégaoctet. Un mémoire qui mesure le gaspillage en octets et le convertit en ariary à l\'heure produit donc une information lisible par la direction financière autant que par les ingénieurs réseau.' },

  { h3: 'Cadre réglementaire et limites d\'accès' },
  { p: 'Le cadre réglementaire malgache laisse les prix libres : la loi 2005-023 ne donne pas à l\'autorité de régulation le pouvoir de fixer les tarifs, mais l\'autorité dispose d\'un pouvoir d\'interpellation qu\'elle a exercé en octobre 2025 en convoquant les trois opérateurs après une vague de plaintes. Les taxes sectorielles représentent un enjeu public débattu dans la presse de novembre 2025, les opérateurs subordonnant toute baisse tarifaire à une révision de leur fiscalité. L\'autorité tient par ailleurs un observatoire du marché qui publie des indicateurs de couverture et de qualité de service, et procède à l\'homologation des matériels : ce sont des données publiques mobilisables pour situer un lien audité dans le paysage national.' },
  { p: 'Une contrainte locale pèse au moins autant que la réglementation des télécoms : l\'alimentation électrique. Les délestages récurrents de la compagnie nationale, documentés par la presse et par les institutions financières internationales tout au long de 2025, interrompent les campagnes de mesure comme ils interrompent les services. La conception du banc en tire les conséquences : la reprise après interruption y est native, une campagne interrompue reprend là où elle s\'était arrêtée, et la fenêtre de trois minutes par événement borne la perte maximale. Ce qui aurait pu être une commodité d\'ingénierie devient ici une exigence du terrain, intégrée dès la conception du protocole.' },
  { p: 'La même logique gouverne le choix de la non-intrusion. Les équipements du cœur de réseau appartiennent aux opérateurs : aucune modification de configuration n\'y est possible, et la moindre expérimentation sur lien de production consommerait un volume prépayé. Les mesures se conduisent donc depuis le poste client, sur des liens reconstitués, et les audits réels se limitent à des sondes légères. Cette contrainte, imposée par le terrain, devient une qualité méthodologique : la démarche s\'applique à toute institution sans négociation avec son opérateur.' },

  { h3: 'Le trafic de Météo Madagascar' },
  { p: 'Le trafic réel de l\'institution donne au problème sa substance. La première famille est critique et légère : les messages d\'observation des stations automatiques rejoignent le Système mondial de télécommunication de l\'Organisation météorologique mondiale, les prévisionnistes consultent les tableaux de bord en continu, et les alertes cycloniques partent pendant la saison du sud-ouest de l\'océan Indien, de novembre à avril, quand chaque minute compte pour la protection des populations. Ces échanges se comptent en kilooctets ; leur valeur dépend entièrement de leur ponctualité.' },
  { p: 'La seconde famille est massive et patiente : les images satellitaires reçues quotidiennement, les sorties des modèles numériques de prévision, les sauvegardes de bases de données. Ces transferts se comptent en gigaoctets ; ils tolèrent la nuit et l\'attente, mais ils doivent passer. La taille des fichiers ne dit rien de leur urgence : une alerte de quelques kilooctets vaut infiniment plus qu\'une image de plusieurs gigaoctets, et c\'est précisément le petit trafic qui souffre quand le gros sature le lien partagé.' },
  { p: 'Cette coexistence définit le cahier des charges implicite de la direction des systèmes d\'information : garantir au trafic critique un temps de réponse stable, même pendant les transferts massifs, sans sacrifier le débit de ces derniers. Le mémoire traduit ce cahier des charges en critère mesurable, le taux de respect d\'échéance, et en garde-fou, le débit utile du flux de masse : les deux seront mesurés ensemble, cellule par cellule, dans la partie pratique.' },

  { h2: 'Problématique et questions de recherche' },
  { p: 'Les applications opérationnelles de Météo Madagascar, télémétrie, tableaux de bord, alertes, partagent leurs liens d\'accès avec des transferts de masse. Quand un tel transfert sature un lien, les files des équipements grossissent et le temps de réponse du petit trafic se dégrade, sans que le débit mesuré ne baisse : c\'est le bufferbloat. Les remèdes connus, les disciplines de file actives et les contrôles de congestion modernes, sont documentés dans la littérature mais aucun chiffre local n\'existait pour décider de leur déploiement sur les liens de l\'institution.' },
  { p: 'Les outils publics ne comblent pas ce manque, pour une raison de principe autant que de fonction : ils s\'exécutent sur des liens réels dont l\'état n\'est pas contrôlé, ils observent des symptômes sans permettre la comparaison reproductible de configurations, et aucun d\'entre eux ne connaît le prix du gigaoctet prépayé. La mesure locale exige donc autre chose : un audit léger pour la vérité de terrain, un banc reproductible pour la comparaison, et un modèle de coût qui parle la langue du budget. C\'est l\'objet de ce travail.' },
  { p: 'La problématique s\'énonce alors ainsi : comment, depuis un poste client et sans modifier l\'infrastructure de production, évaluer de manière reproductible la capacité d\'un lien d\'accès contraint à protéger le trafic critique pendant les transferts de masse, et quelles politiques de configuration recommander à partir de mesures vérifiables ?' },
  { p: 'Trois questions de recherche découlent de cette problématique, chacune adossée à un dispositif de test précis. Elles s\'énoncent dans le {tabRef:rq} et structurent le reste du mémoire : la partie théorique construit les instruments de réponse, la partie pratique apporte les réponses mesurées.' },
  { table: {
    id: 'rq',
    caption: 'Questions de recherche et dispositifs de réponse',
    widths: [12, 48, 40],
    header: ['N°', 'Question', 'Dispositif'],
    rows: [
      ['RQ1', 'Les liens d\'accès accessibles présentent-ils des symptômes de dégradation de latence sous charge ?', 'Audit non intrusif depuis un poste client, comparaison repos contre charge'],
      ['RQ2', 'Les disciplines actives protègent-elles le trafic critique mieux que la file simple, à débit de masse acceptable ?', 'Banc reproductible, matrice profil × discipline × contrôle de congestion, portes de qualité'],
      ['RQ3', 'Quelle configuration recommander aux équipements locaux, à quel coût ?', 'Interprétation des mesures au regard des tarifs réels et des équipements maîtrisés'],
    ] } },

  { h2: 'Objectifs du travail' },
  { p: 'Trois objectifs découlent de ces questions. Le premier est méthodologique : disposer d\'une méthode d\'audit non intrusive applicable à tout lien accessible depuis un poste autorisé. Le deuxième est expérimental : disposer d\'un banc reproductible qui compare les politiques de gestion de file et de contrôle de congestion sur des profils de liens représentatifs du contexte, avec un gel vérifiable des données. Le troisième est opérationnel : produire des recommandations pour les équipements locaux, chiffrées en gain de latence protégée et en coût de gaspillage évité, accompagnées de la configuration réseau correspondante.' },
  { p: 'La vérifiabilité traverse ces trois objectifs comme un fil conducteur. Un résultat qui n\'existerait que dans le mémoire vaudrait peu : chaque chiffre cité doit pouvoir être recalculé depuis une archive empreintée, chaque figure régénérée depuis les données gelées, chaque recommandation confrontée à sa cellule d\'origine. C\'est cette chaîne, de la mesure au chiffre publié, que la partie suivante construit.' },
];
