// Partie III : Méthodologie, analyse de l'existant (onze points).
module.exports = [
  { h1: `PARTIE III : MÉTHODOLOGIE, ANALYSE DE L'EXISTANT` },

  { p: `La méthode retenue est l'analyse de l'existant, appliquée à l'environnement de mesure : elle précède et fonde la proposition de solutions et le choix de l'outil. Cette partie applique systématiquement les onze points de la méthode aux trois couches de l'environnement, puis en tire une synthèse critique qui débouche sur l'écart que la solution devra combler.` },

  { h2: `Cadre de l'analyse` },
  { p: `L'analyse de l'existant est la discipline centrale de la méthode retenue. Elle consiste à inventorier, décrire et critiquer l'environnement dans lequel un projet s'inscrit, afin de dégager les insuffisances que la solution devra combler. Dans un projet de mesure réseau comme celui-ci, le mot « existant » désigne trois objets distincts : le terrain (les liens d'accès malgaches que l'on cherche à caractériser), l'état de l'art instrumental (les outils de mesure disponibles et leurs lacunes), et le banc expérimental (l'infrastructure dont on dispose pour produire des résultats contrôlés). Les onze points de la méthode sont appliqués systématiquement à ces trois couches.` },
  { p: `L'application de la méthode d'analyse de l'existant à un objet de recherche présente une difficulté spécifique : alors que l'analyse de l'existant d'entreprise vise à inventorier un système existant dans l'objectif de le remplacer ou de le faire évoluer, l'analyse de l'existant d'un environnement de mesure vise à identifier les lacunes instrumentales que la solution devra combler. La nature de la « solution » est différente : ce n'est pas un nouveau système d'information, mais un nouvel instrument de mesure. La méthode reste valable, mais chaque point doit être réinterprété pour ce contexte, ce que le {tabRef:methode} explicite.` },
  { table: {
      id: 'methode',
      caption: `Correspondance entre les onze points de la méthode et les trois couches de l'environnement de mesure.`,
      header: ['Point de la méthode', 'Couche concernée', 'Objet dans le travail'],
      rows: [
        ['1. Topologie réseau', 'Banc et terrain', 'Topologie du banc (ns-A, goulot, ns-B) et lien 4G réel'],
        ['2. Type de réseau', 'Terrain', 'Lien émulé, lien 4G réel, profil VSAT'],
        ['3. Équipement d\u2019interconnexion', 'Banc', 'Composants noyau : veth, netem, TBF, fq_codel'],
        ['4. Postes de travail', 'Banc', 'Machine virtuelle unique et machine hôte'],
        ['5. Serveurs', 'Banc', 'Binaire cgo-linux, serveur iperf3'],
        ['6. Gateways', 'Terrain et banc', 'Modem 4G ou partage de connexion vers l\u2019Internet'],
        ['7. Partage', 'Banc', 'Archive reproductible : CSV, Zenodo, chaîne SHA-256'],
        ['8. Routage', 'Banc', 'Épinglage de route vers le goulot, vérifié par la porte G2'],
        ['9. Disponibilité', 'Terrain et banc', 'Délestage JIRAMA, reprise sur incident, mode hors ligne'],
        ['10. Surveillance', 'Banc', 'Oracle tc -s, ping horodaté, TCP_INFO, tcpdump'],
        ['11. Analyse des trafics', 'Terrain', 'Caractérisation 4G : profil diurne, RTT, pertes, coût'],
      ],
      widths: [26, 20, 54],
  } },
  { p: `Le {tabRef:methode} présente la correspondance entre les onze points de la méthode et les trois couches de l'environnement de mesure. Cette correspondance explicite est une précaution méthodologique : elle évite que le lecteur ne projette sur le travail les attendus d'une analyse de l'existant d'entreprise (inventaire d'armoires, de câblage, d'annuaire) et reconnaisse au contraire une adaptation rigoureuse de la méthode à un objet de recherche. Chaque point est développé ci-dessous avec son tableau, une analyse de l'existant et une critique, selon la structure imposée par la méthode.` },

  { h2: `Application des onze points` },

  { h3: `Topologie réseau` },
  { p: `Le banc expérimental comprend deux espaces de noms réseau, ns-A et ns-B, reliés par une paire veth nommée thesis-veth0 [51]. L'espace ns-A fait office d'émetteur : il héberge les générateurs de trafic (iperf3, BBR, CUBIC) et le binaire cgo-linux qui porte l'oracle, les détecteurs et le contrôleur adaptatif. L'espace ns-B est le récepteur et porte le serveur iperf3 ainsi que tcpdump [52] pour les captures de référence. Sur l'interface thesis-veth0, une pile de disciplines de file (qdisc) impose les caractéristiques du lien : netem pour le délai et la perte, TBF pour la limitation de débit, et fq_codel pour la gestion active de l'attente [49][50]. Les offloads matériels sont désactivés sur cette interface afin d'éviter que les optimisations de la carte réseau virtuelle ne masquent les effets de la congestion. La {figRef:banc} présente cette topologie.` },
  { fig: { id: 'banc', file: 'fig03-banc', caption: `Topologie du banc expérimental : espaces de noms, goulot façonné, canaux d'observation.` } },
  { p: `Deux canaux d'observation indépendants surveillent le goulot sans faire partie du chemin de données de la charge. Le premier est l'oracle noyau, qui lit les compteurs de file via tc -s class show à une fréquence de 10 Hz. Le second est un ping horodaté par le noyau à 5 Hz. À ces canaux s'ajoutent la covariable TCP_INFO lue à 1 Hz et la capture tcpdump complète. La couche de surveillance est donc triple : compteurs exacts (oracle), mesures indépendantes (ping), et archives brutes (tcpdump).` },
  { table: {
      id: 'topo',
      caption: `Éléments de la topologie du banc.`,
      header: ['Désignation', 'Rôle', 'Adresse / paramètres'],
      rows: [
        ['ns-A', 'Émetteur (générateurs de trafic)', 'Espace de noms isolé'],
        ['thesis-veth0', 'Goulot (netem, TBF, qdisc)', 'Paire veth, offloads désactivés'],
        ['ns-B', 'Récepteur', '10.200.1.2, portée lien'],
        ['Canal ping', 'Mesure indépendante du RTT', 'Horodatage noyau, 5 Hz'],
        ['Oracle', 'Compteurs de file', 'tc -s class show, 10 Hz'],
      ],
      widths: [24, 38, 38],
  } },
  { p: `Le {tabRef:topo} résume les éléments de la topologie. Les adresses IP sont en portée lien : il n'y a pas de routage entre ns-A et ns-B, seulement un lien direct.` },
  { p: `La topologie du terrain, qui est utilisée pour la phase de validation sur lien réel, est symétriquement simple : un modem 4G ou un téléphone en partage de connexion relie le banc à l'antenne de l'opérateur. Aucun équipement actif supplémentaire (routeur, commutateur) n'est interposé entre le banc et le réseau mobile, afin de ne pas introduire de source de gigue ou de perte qui ne viendrait pas du lien d'accès lui-même. La différence fondamentale entre les deux topologies est la connaissance de la vérité terrain : sur le banc, elle est connue par construction ; sur le terrain, elle est l'objet de la mesure.` },

  { h3: `Type de réseau` },
  { p: `Trois types de liens sont étudiés. Le premier est le lien émulé, obtenu en façonnant la paire veth avec netem et TBF. Il offre une vérité terrain connue par construction : le débit, le délai et le taux de perte sont imposés par le noyau et vérifiables par l'oracle. Le second est le lien 4G réel, obtenu en connectant le banc à l'opérateur via une carte SIM prépayée. Ce lien ancre les résultats dans les conditions réelles du contexte malgache : un coût par octet élevé, une gigue et des pertes sporadiques, un effondrement de capacité aux heures de pointe. Le troisième est le profil VSAT, rejoué en émulation avec un RTT de l'ordre de 600 ms, pour couvrir le cas des zones rurales non couvertes par la 4G.` },
  { p: `Le profil VSAT mérite une attention particulière car il représente le cas le plus défavorable de la connectivité malgache. Les zones rurales, qui ne sont pas desservies par le réseau mobile, accèdent à l'Internet par des liaisons satellite dont le RTT atteint 600 ms en raison de la distance géostationnaire. Le produit débit-délai élevé qui en résulte rend inefficaces les mécanismes de contrôle de congestion classiques, qui confondent le délai de propagation avec le délai de file. Inclure ce profil dans la matrice expérimentale permet de vérifier que les solutions proposées restent efficaces dans les conditions les plus extrêmes.` },
  { p: `Les câbles sous-marins METISS [6] et 2Africa [9] ont renforcé la capacité internationale de Madagascar, mais la contrainte se situe désormais au dernier kilomètre radio, où la capacité partagée d'une cellule 4G s'effondre aux heures de pointe. Les connexions des opérateurs locaux ne sont pas redondantes : chaque carte SIM correspond à un seul opérateur, sans secours. Cette observation justifie la redondance prévue au bras terrain, qui utilise deux opérateurs sur deux chemins matériels distincts.` },
  { table: {
      id: 'types',
      caption: `Types de liens de l'environnement de mesure.`,
      header: ['Type', 'Débit nominal', 'RTT typique', 'Caractéristique dominante'],
      rows: [
        ['Lien émulé (veth + netem + TBF)', '50 Mbit/s, configurable', '50 à 160 ms imposés', 'Vérité terrain connue par construction'],
        ['Lien 4G réel (SIM prépayée)', 'Variable, effondrement diurne', 'Variable', 'Coût par octet élevé, gigue et pertes'],
        ['Profil VSAT (émulé)', 'Faible, garanti', '~600 ms', 'Haut produit débit-délai'],
      ],
      widths: [30, 24, 18, 28],
  } },
  { p: `Le {tabRef:types} résume les trois types de liens. Leur diversité permet de confronter les mêmes détecteurs et disciplines de file à des conditions de propagation et de coût radicalement différentes. La distinction entre ces trois types est fondamentale pour la généralisation des résultats. Un détecteur qui fonctionne sur un lien émulé à 50 ms de RTT peut être testé sur le profil VSAT à 600 ms pour vérifier sa robustesse au produit débit-délai. De même, un réglage de façonneur adaptatif validé en émulation peut être confronté au comportement réel du lien 4G, qui introduit des variations non modélisées par les paramètres netem. Cette confrontation entre l'idéal (lien émulé) et le réel (lien 4G) est au cœur du protocole de validation.` },

  { h3: `Équipement d'interconnexion` },
  { p: `Dans un banc logiciel, les équipements d'interconnexion sont des composants du noyau Linux plutôt que des boîtiers physiques. Le goulot thesis-veth0 reçoit une pile de qdisc composée de trois éléments. netem [49] impose le délai de propagation, la gigue et le taux de perte. TBF [50] limite le débit à 50 Mbit/s nominal par un mécanisme à seau de jetons. fq_codel [30] assure la gestion active de file, en attribuant une file par flux et en appliquant l'algorithme CoDel pour maintenir le temps de séjour des paquets sous la cible de 5 ms. Les espaces de noms ns-A et ns-B [51] assurent l'isolation de la couche réseau entre l'émetteur et le récepteur.` },
  { p: `Le choix de composants noyau plutôt que d'équipements physiques présente trois avantages. Le premier est la reproductibilité : la configuration est décrite dans un script shell exécutable sur toute machine Linux. Le second est l'accès aux compteurs internes : l'oracle lit les statistiques exactes de la file, ce qu'aucun équipement réseau commercial ne permet. Le troisième est le coût : le banc fonctionne sur une seule machine virtuelle, sans matériel spécifique.` },
  { table: {
      id: 'interco',
      caption: `Équipements d'interconnexion logiciels du banc.`,
      header: ['Désignation', 'Caractéristiques', 'Emplacement'],
      rows: [
        ['Paire veth thesis-veth0', 'Lien virtuel point à point, offloads désactivés', 'Noyau, entre ns-A et ns-B'],
        ['netem', 'Délai, gigue, perte (0,1 % perte, 10 ms gigue en contexte 4G)', 'qdisc du goulot [49]'],
        ['TBF', 'Limiteur de débit à jeton, 50 Mbit/s nominal', 'qdisc du goulot [50]'],
        ['fq_codel', 'File par flux et algorithme CoDel', 'qdisc enfant, réglage par défaut [30]'],
        ['Espaces de noms ns-A, ns-B', 'Isolation émetteur et récepteur', 'Noyau [51]'],
      ],
      widths: [28, 42, 30],
  } },
  { p: `Le {tabRef:interco} énumère les équipements d'interconnexion logiciels. Chacun correspond à une fonction réseau identifiable : retard, limitation, gestion de file, isolement. Le paramétrage de ces composants est critique pour la reproductibilité des expériences. netem est configuré avec des valeurs fixes de délai (50 ms, 160 ms, 600 ms selon le profil), une gigue de 10 ms en contexte 4G et un taux de perte de 0,1 %. Ces valeurs sont issues des observations du terrain et reproduisent les conditions d'un lien d'accès malgache contraint. TBF est réglé à 50 Mbit/s nominal avec une taille de rafale calibrée pour éviter les sous-utilisations intempestives. fq_codel utilise le réglage par défaut du noyau, qui constitue le scénario de base de l'expérience E3.` },
  { p: `Un aspect important est l'interaction entre ces trois qdisc. netem et TBF sont placés en tête de pile, suivis de fq_codel comme discipline enfant. Cette hiérarchie garantit que le délai et la limitation de débit sont appliqués avant la gestion de file, ce qui correspond à l'ordre logique d'un goulot réel : le délai de propagation est une propriété physique, la limitation de débit est une contrainte d'interface, et la gestion active de l'attente est un correctif logiciel qui agit sur les paquets en attente.` },
  { p: `La désactivation des offloads matériels sur thesis-veth0 constitue un invariant de l'expérimentation que le protocole de vérification contrôle à chaque lancement. Les mécanismes tels que TSO, GSO, GRO ou LRO ont pour effet de regrouper les paquets avant de les soumettre à la file, ce qui masque la dynamique réelle de la congestion et fausse les compteurs de l'oracle. Leur désactivation est vérifiée par la porte G1 du protocole.` },

  { h3: `Postes de travail` },
  { p: `L'ensemble du dispositif fonctionne sur une machine unique : une machine virtuelle Ubuntu 24.04 LTS [54] dotée de 2 cœurs vCPU, 4 Go de RAM et au moins 40 Go d'espace disque. Le noyau 6.8 assure la prise en charge des fonctionnalités réseau utilisées (netem, TBF, fq_codel, espaces de noms). La machine hôte, un portable sur batterie, fournit l'alimentation de secours nécessaire lors des délestages électriques. Le choix d'une machine unique simplifie le déploiement et garantit que l'ensemble des composants est synchronisé : l'oracle, les générateurs de trafic et les sondes partagent la même horloge.` },
  { table: {
      id: 'poste',
      caption: `Poste de mesure.`,
      header: ['Désignation', 'Caractéristiques', 'Système d\u2019exploitation', 'Rôle'],
      rows: [
        ['VM cgo', '2 vCPU, 4 Go RAM, \u2265 40 Go disque, noyau 6.8', 'Ubuntu 24.04 LTS [54]', 'Banc expérimental complet'],
        ['Machine hôte', 'Portable sur batterie', 'Indifférent', 'Alimentation de secours lors des coupures'],
      ],
      widths: [16, 34, 22, 28],
  } },
  { p: `Le {tabRef:poste} décrit le poste de mesure. La VM unique réduit la variabilité due aux horloges distribuées et garantit que le temps d'horloge mesuré par l'oracle et par les sondes est identique. Le choix d'une machine virtuelle plutôt que d'un serveur dédié présente un avantage pratique pour le contexte malgache : le portable qui sert de machine hôte peut être transporté sur le terrain, rechargé sur batterie lors des délestages, et reconnecté au réseau électrique dès que le courant revient. La VM peut être suspendue et reprise sans perte de données, ce qui est indispensable dans un environnement où les coupures sont imprévisibles.` },

  { h3: `Serveurs` },
  { p: `Deux services tournent sur le poste de mesure. Le binaire cgo-linux, écrit en Go [55], est un exécutable statique d'environ 13 Mo. Il héberge quatre fonctions critiques : l'oracle noyau qui collecte les compteurs de file, les cinq détecteurs d'événements de congestion, le contrôleur adaptatif pour l'expérience E3, et la chaîne d'intégrité qui archive les résultats. Le serveur iperf3 [48] génère et mesure le trafic de charge TCP et UDP. Aucun des deux services n'expose d'interface vers l'extérieur du banc : les communications sont locales à l'espace de noms, ce qui rend l'authentification sans objet.` },
  { table: {
      id: 'services',
      caption: `Services du banc.`,
      header: ['Désignation', 'Caractéristiques', 'Service', 'Accès'],
      rows: [
        ['cgo-linux', 'Binaire Go statique, ~13 Mo', 'Oracle, détection, contrôle, manifeste', 'Local uniquement'],
        ['iperf3', 'Serveur et client de mesure', 'Trafic TCP/UDP de charge', 'Local (ns-A vers ns-B)'],
      ],
      widths: [16, 30, 32, 22],
  } },
  { p: `Le {tabRef:services} résume les deux services. Le choix de Go pour cgo-linux est motivé par la facilité de déploiement (binaire statique, aucune dépendance) et la garantie d'identité de comportement entre l'environnement de développement et le banc de mesure. Les deux services s'exécutent dans l'espace de noms ns-A et communiquent avec ns-B par des sockets standard. Aucun des deux n'utilise de mécanisme de communication inter-processus qui nécessiterait des privilèges particuliers ou des points de montage spécifiques, ce qui facilite le déploiement sur une VM vierge. Le démarrage du banc se résume à l'exécution d'un script shell unique qui crée les espaces de noms, configure les qdisc, lance les deux binaires et vérifie les portes G1 et G2.` },
  { p: `L'architecture sans dépendance externe de cgo-linux présente un avantage supplémentaire pour le contexte malgache : le binaire peut être distribué sur une clé USB et exécuté sur toute machine Linux sans installation préalable ni connexion internet. Cette propriété est déterminante dans un environnement où la bande passante est chère et où les gestionnaires de paquets peuvent être incomplets.` },

  { h3: `Gateways` },
  { p: `La passerelle vers l'extérieur est le lien 4G du bras terrain, dont la {figRef:g4} présente la topologie. Le modem 4G, acquis localement auprès d'un distributeur agréé conformément à l'homologation des équipements terminaux exigée par l'ARTEC [24], assure la translation d'adresse côté opérateur. Aucun pare-feu local n'est nécessaire : le banc n'expose aucun service vers l'Internet. En alternative, le partage de connexion d'un téléphone déjà homologué peut remplacer le modem dédié. La loi n° 2014-038 sur la protection des données [26] est respectée par construction : les captures portent sur du trafic synthétique, à l'exclusion de tout trafic d'usagers tiers.` },
  { fig: { id: 'g4', file: 'fig04-4g', caption: `Topologie du lien 4G réel : banc de mesure, passerelle homologuée, réseau de l'opérateur.` } },
  { table: {
      id: 'gateway',
      caption: `Passerelle vers l'Internet.`,
      header: ['Désignation', 'Caractéristiques', 'Fonctionnalités activées'],
      rows: [
        ['Modem 4G (ou téléphone en partage)', 'Carte SIM prépayée, opérateur local', 'NAT opérateur, pas de pare-feu local, trafic de mesure uniquement'],
      ],
      widths: [30, 30, 40],
  } },
  { p: `Le {tabRef:gateway} décrit la passerelle. Le lien 4G est le seul point de contact avec l'Internet, ce qui permet d'isoler les phénomènes mesurés des artefacts de routage ou de filtrage qui affecteraient un trafic traversant plusieurs sauts. L'acquisition du modem 4G auprès d'un revendeur agréé garantit la conformité aux exigences d'homologation de l'ARTEC [24]. Cette homologation certifie que l'équipement respecte les normes d'émission radio et de compatibilité électromagnétique applicables à Madagascar, ce qui écarte les risques d'interférence avec les équipements du réseau de l'opérateur. Un téléphone grand public utilisé en partage de connexion satisfait à la même obligation, puisqu'il a déjà été homologué avant sa mise sur le marché.` },
  { p: `Le trafic de mesure est le seul trafic qui transite par la passerelle. Cette isolation est assurée par la configuration réseau du banc : les espaces de noms ne possèdent pas de route par défaut vers l'Internet, et le modem est connecté à un espace de noms dédié qui ne contient que le client de mesure. Cette architecture évite que des mises à jour système, des requêtes DNS intempestives ou des services d'arrière-plan ne contaminent les mesures.` },

  { h3: `Partage` },
  { p: `Le partage des données du projet prend la forme d'une archive reproductible. Celle-ci comprend les tables gelées e1onsets.csv et e3events.csv, qui contiennent les résultats des expériences E1 et E3, les paquets de preuves par événement (captures tcpdump et journaux d'oracle), le manifeste chaîné par SHA-256 qui garantit l'intégrité de chaque fichier, et le dépôt Zenodo [53] qui attribue un DOI pérenne à l'ensemble. Tous les formats sont ouverts : CSV pour les données tabulaires, JSON pour les métadonnées. La régénération des figures s'effectue par une commande unique, ce qui permet à tout tiers de vérifier chaque nombre publié.` },
  { p: `Ce partage n'est pas un service de fichiers d'entreprise : c'est la surface de vérification scientifique du travail. Il répond aux exigences de la culture de mesure des conférences PAM, IMC et TMA, qui imposent que les données et le code soient archivés et accessibles pour permettre la réplication indépendante des résultats.` },
  { p: `La procédure de vérification par un tiers se déroule en trois étapes. Premièrement, le téléchargement du dépôt Zenodo et la vérification des sommes SHA-256 garantissent que les données n'ont pas été modifiées. Deuxièmement, l'exécution du script de régénération sur un poste non lié au projet produit des figures et des nombres identiques à ceux du mémoire. Troisièmement, la comparaison des résultats de l'oracle avec les captures brutes de tcpdump permet de vérifier qu'aucune étape de la chaîne de traitement n'a introduit de biais.` },
  { p: `La publication sur Zenodo [53] garantit la pérennité de l'archive indépendamment de l'hébergement universitaire : le DOI attribué reste résoluble même si le dépôt est déplacé ou si le laboratoire change de politique d'accès. Cette indépendance est capitale pour la crédibilité scientifique du travail, car elle évite que la vérification des résultats dépende de la disponibilité d'une infrastructure maintenue par l'auteur.` },

  { h3: `Routage` },
  { p: `Le routage du banc est statique et volontairement contraint. Le trafic de charge est épinglé vers le goulot par une règle de routage par politique (policy routing) : toute communication entre ns-A et ns-B passe nécessairement par thesis-veth0. Cet épinglage est vérifié en continu par la porte G2, qui s'assure que la file se constitue après quinze secondes de charge. L'absence d'épinglage serait détectée comme un sabotage (NC-1) : un trafic qui contournerait le goulot ne traverserait pas la file et fausserait les mesures. Aucun protocole de routage dynamique (RIP, OSPF, BGP) n'est utilisé, le banc ne comportant que deux espaces de noms et un seul lien.` },
  { p: `Le choix d'un routage statique plutôt que dynamique n'est pas une simplification, mais une décision méthodologique. Un protocole de routage dynamique introduirait une source de variabilité supplémentaire : les temps de convergence, les annonces de préfixe et les changements de métrique affecteraient le trafic de mesure sans rapport avec la congestion du goulot. L'épinglage par policy routing garantit que le chemin emprunté par chaque paquet est déterministe et connu, ce qui est une condition nécessaire pour que l'oracle puisse attribuer chaque variation de file à la charge et non à un événement de routage.` },

  { h3: `Disponibilité` },
  { p: `La disponibilité du dispositif de mesure est analysée point par point, en distinguant le banc et le terrain. Le {tabRef:dispo} présente l'état de l'existant pour chaque ressource et la conséquence pour le projet.` },
  { table: {
      id: 'dispo',
      caption: `Analyse de la disponibilité.`,
      header: ['Ressource', 'État de l\u2019existant', 'Conséquence pour le projet'],
      rows: [
        ['Applications', 'Binaire cgo-linux s\u2019exécute sans dépendance externe', 'Fonctionnement hors ligne, aucune mise à jour en campagne'],
        ['Données', 'Archive gelée, hachée, régénérable', 'Reprise sur incident sans perte ni duplication'],
        ['Ressources', '2 vCPU, 4 Go RAM, ~8 Go de captures', 'Épinglage processeur et quotas pour contenir la variance'],
        ['Internet', 'Requis uniquement en phase de préparation', 'Mode avion pendant les campagnes et à la soutenance'],
        ['Énergie', 'Délestage JIRAMA, coupures de plusieurs heures [16][19]', 'Points de contrôle par événement, reprise après coupure, batterie de secours'],
        ['Sauvegarde', 'Manifeste SHA-256, dépôt Zenodo', 'Restauration et vérification par un tiers'],
        ['QoS', 'Objet même de l\u2019étude', 'Mesurée par l\u2019oracle et les canaux indépendants'],
      ],
      widths: [16, 40, 44],
  } },
  { p: `Le {tabRef:dispo} analyse la disponibilité pour sept ressources critiques. La contrainte énergétique est la plus contraignante : les délestages de la JIRAMA [16] peuvent durer plusieurs heures et surviennent sans préavis fiable. Le dispositif intègre donc des points de contrôle par événement, une reprise automatique après coupure et une batterie de secours sur la machine hôte.` },
  { p: `La ressource Internet appelle également une attention particulière. Pendant les phases de préparation, la connexion est nécessaire pour télécharger les mises à jour et les dépendances. Pendant les campagnes de mesure et lors de la soutenance, le banc passe en mode avion : toute communication vers l'extérieur est coupée pour éviter que des mises à jour intempestives ou des alertes système ne perturbent les mesures. Les données sont archivées localement et synchronisées avec Zenodo une fois la campagne terminée.` },

  { h3: `Surveillance` },
  { p: `La couche de surveillance du banc est l'apport central du projet. Elle se distingue des outils de supervision classiques (Zabbix, Nagios) par deux propriétés : elle mesure la congestion contre une vérité terrain connue, et elle opère à une fréquence suffisante pour capturer les évolutions rapides du délai de file. L'oracle noyau lit les compteurs de file à 10 Hz via tc -s class show. Le canal ping horodaté fournit une mesure indépendante du RTT à 5 Hz. La covariable TCP_INFO est collectée à 1 Hz. tcpdump enregistre l'intégralité du trafic pour les campagnes principales.` },
  { p: `L'état de l'art de la mesure du bufferbloat est représenté par flent [43][44] et les outils de bufferbloat.net [57]. Flent orchestre plusieurs sondes simultanées (netperf, iperf, ping) et produit des séries temporelles reproductibles. Mais ces instruments mesurent des liens réels dont la vérité terrain est inconnue : ils observent des symptômes, pas des événements datés. La présente approche inverse la logique : elle fournit d'abord la vérité terrain (oracle), puis compare les observations des instruments tiers à cette référence.` },
  { p: `La fréquence d'échantillonnage de chaque canal est choisie en fonction du phénomène observé. L'oracle à 10 Hz capture les variations de file à l'échelle de la centaine de millisecondes, ce qui correspond au temps de réponse de CoDel et des détecteurs de gradient. Le ping à 5 Hz offre une résolution suffisante pour tracer l'évolution du RTT sans alourdir le lien. TCP_INFO à 1 Hz fournit une covariable continue sans nécessiter d'horodatage noyau. Ces fréquences sont calibrées pour éviter que les canaux d'observation eux-mêmes ne deviennent une source de charge significative.` },
  { table: {
      id: 'surv',
      caption: `Comparaison des approches de surveillance.`,
      header: ['Outil', 'Grandeur mesurée', 'Vérité terrain', 'Retenu'],
      rows: [
        ['Oracle tc -s (10 Hz)', 'Compteurs de file exacts', 'Oui (lecture noyau)', 'Oui'],
        ['ping horodaté (5 Hz)', 'RTT', 'Canal indépendant', 'Oui'],
        ['TCP_INFO (1 Hz)', 'RTT et retransmissions par socket', 'Covariable', 'Oui'],
        ['tcpdump', 'Captures de référence', 'Preuve brute', 'Oui'],
        ['flent [43]', 'Sondes agrégées', 'Non (lien réel)', 'Comparateur'],
        ['Zabbix, Nagios', 'Disponibilité, ressources', 'Non (supervision)', 'Non'],
      ],
      widths: [26, 32, 24, 18],
  } },
  { p: `Le {tabRef:surv} compare les approches de surveillance. Seuls les outils qui fournissent une vérité terrain ou un canal indépendant sont retenus pour les campagnes principales. flent est conservé comme comparateur dans le protocole de validation.` },

  { h3: `Analyse des trafics réseaux` },
  { p: `L'équivalent de l'interview des utilisateurs, prévue par la méthode d'analyse de l'existant, est, dans ce projet, la caractérisation passive du lien 4G réel pendant la phase de préparation. Des relevés continus de RTT, de débit et de pertes sont effectués sur des créneaux diurnes, sans trafic de charge, afin d'établir le profil de base du lien. Les captures révèlent trois régularités. Premièrement, un effondrement diurne de la capacité aux heures de pointe (perte de 50 à 80 % du débit nominal). Deuxièmement, un élargissement de la distribution du RTT qui précède le franchissement de la moyenne, ce qui est précisément le signal que le test de Kolmogorov-Smirnov est conçu pour capter. Troisièmement, des pertes sporadiques avec gigue, qui imposent des mécanismes de robustesse dans le protocole de mesure.` },
  { p: `Ces observations justifient les trois familles d'événements de la matrice expérimentale : l'échelon (chute brutale de capacité), la rampe (dégradation progressive), et l'effondrement diurne (chute cyclique de capacité). Elles justifient également les quatre contextes : propre (aucune perturbation), 50 ms, 160 ms, et 4G avec 0,1 % de perte et 10 ms de gigue. Le coût du forfait, de l'ordre de 30 000 MGA pour quelques gigaoctets, est relevé comme grandeur économique du terrain.` },
  { p: `La caractérisation passive du lien 4G remplit également un rôle de calibration pour l'émulation. Les paramètres de netem (délai, gigue, taux de perte) sont ajustés pour que le comportement du lien émulé reproduise les distributions observées sur le terrain. Cette calibration n'est pas une modélisation complète du canal 4G, ce qui sortirait du périmètre du travail, mais un appariement statistique des premiers moments : la moyenne et la variance du RTT, le taux de perte moyen. L'écart résiduel entre le lien émulé et le lien réel est précisément ce que le protocole de validation permet d'évaluer.` },
  { p: `Les {figRef:diurne} et {figRef:ecdf4g} illustrent deux régularités observées lors de cette caractérisation. La {figRef:diurne} montre l'effondrement diurne de la capacité aux heures de pointe, avec une perte de débit pouvant atteindre 80 % entre 12 h et 14 h et entre 18 h et 21 h. La {figRef:ecdf4g} présente la distribution cumulative du RTT, qui révèle un élargissement progressif de la distribution avant que la moyenne ne franchisse un seuil visible. Ce phénomène est le signal que le test de Kolmogorov-Smirnov exploité dans l'expérience E1 est conçu pour détecter : un changement dans la forme de la distribution avant que la tendance centrale ne se déplace.` },
  { fig: { id: 'diurne', file: 'fig05-diurne', caption: `Profil diurne de capacité du lien 4G : effondrement aux heures de pointe.` } },
  { fig: { id: 'ecdf4g', file: 'fig06-ecdf-4g', caption: `Distribution cumulative du RTT sur le lien 4G : élargissement de la distribution avant franchissement de seuil.` } },

  { h2: `Synthèse de l'existant` },
  { p: `L'analyse des onze points conduit à trois constats qui se renforcent mutuellement. Le terrain malgache est un lien hautement contraint : un RTT élevé et variable, une capacité diurne qui s'effondre aux heures de pointe, un coût par octet élevé qui rend le gaspillage économiquement significatif, et une alimentation électrique instable qui impose des mécanismes de reprise. L'état de l'art de la mesure, représenté par flent et les outils publics, observe ces liens sans vérité terrain : les instruments disponibles mesurent des symptômes (latence, pertes) sans pouvoir les rattacher à des événements datés. Le banc expérimental, en revanche, fournit une vérité terrain par construction grâce aux compteurs noyau, à l'épinglage vérifié et à l'archive chaînée.` },
  { p: `L'écart entre les deux est le point de départ du travail : il manque un instrument qui combine un trafic réaliste, une vérité terrain datée et une vérification indépendante. Cet écart fonde les trois questions de recherche.` },
  { p: `La synthèse de l'analyse de l'existant met en évidence un résultat central : la force du travail ne réside pas dans un nouvel algorithme ou un nouveau protocole, mais dans l'articulation entre un banc à vérité terrain et un terrain contraint. L'instrument proposé, l'observatoire CGO, n'est pas un simple outil de mesure supplémentaire : c'est un dispositif qui permet de transformer des observations symptomatiques (latence, pertes) en événements datés et falsifiables. Cette transformation est la contribution méthodologique du travail, et elle n'est possible que parce que l'analyse de l'existant a été conduite systématiquement sur les trois couches identifiées.` },
  { p: `Une limitation de cette analyse doit être reconnue. L'analyse de l'existant porte sur un environnement de mesure construit par l'auteur, et non sur un hôpital, une administration ou une entreprise comme le prévoit la méthode d'origine. Il existe donc un risque de circularité : l'analyse de l'existant pourrait être biaisée par le fait que l'auteur est aussi le concepteur du banc. Ce risque est atténué de deux manières. Premièrement, les constats sont fondés sur des mesures objectives (relevés 4G, compteurs noyau) et non sur des déclarations subjectives. Deuxièmement, les onze points sont appliqués avec une grille indépendante du choix de la solution : la critique de l'existant précède la proposition de l'observatoire CGO, qui n'apparaît que dans la partie suivante.` },
  { table: {
      id: 'synthexist',
      caption: `Synthèse de l'analyse de l'existant.`,
      header: ['Constat', 'Fondement (point de la méthode)', 'Conséquence pour le projet'],
      rows: [
        ['Lien hautement contraint', '2, 9, 11', 'Profils expérimentaux réalistes, robustesse aux coupures'],
        ['Mesure sans vérité terrain', '10', 'Apport d\u2019un oracle noyau et de canaux indépendants'],
        ['Banc à vérité terrain disponible', '1, 3, 8', 'Émulation contrôlée avec événements datés'],
        ['Écart : pas d\u2019instrument combinant les trois', 'Synthèse', 'Objet du travail, questions RQ1 à RQ3'],
      ],
      widths: [32, 26, 42],
  } },
  { p: `Le {tabRef:synthexist} synthétise les trois constats et leur conséquence. Chaque constat est rattaché aux points de la méthode qui le fondent. L'écart identifié entre un terrain contraint et un état de l'art sans vérité terrain est l'objet du travail et débouche sur les trois questions de recherche.` },
  { p: `L'écart identifié par l'analyse de l'existant appelle une solution instrumentale : c'est l'objet de la partie suivante, qui propose l'observatoire CGO et justifie le choix de chacun des outils qui le composent.` },
];
