// 03-partie2 — Partie II : considération théorique (20-22 p.)
module.exports = [
  { h1: 'PARTIE II : CONSIDÉRATIONS THÉORIQUES' },
  { p: 'Cette partie expose le cadre théorique du travail. Elle précise d\'abord la méthodologie en deux volets, audit non intrusif et banc d\'essai reproductible. Elle définit ensuite les équations des mesures : percentiles, respect d\'échéance, régularité du lien, score de voix du modèle E, coût du gaspillage et empreinte de vérification. Elle détaille le protocole des campagnes, les algorithmes d\'orchestration et la topologie du banc. Elle close par les matériels.' },

  { h1: 'II.1 Méthodologie' },
  { h2: 'II.1.1 L\'audit non intrusif' },
  { p: 'L\'audit mesure le comportement d\'un lien accessible depuis un poste client autorisé. Il ne modifie aucun équipement : les sondes émises sont du trafic synthétique léger, ping et récupération de petits objets, complétées par un transfert de courte durée pour estimer le débit. Pour chaque lien, l\'audit collecte la latence au repos (p50, p95), la latence des petits objets, le débit utile et la perte, puis rejoue la même mesure pendant une charge courte. La sortie est une ligne archivée par lien, avec le site, le type de lien, l\'opérateur et l\'horaire. Cette méthode répond à la première question de recherche sans jamais s\'approprier le réseau de production : l\'institution n\'expose aucun équipement et aucune donnée opérationnelle.' },
  { h2: 'II.1.2 Le banc reproductible installé sur le poste client' },
  { p: 'Le banc d\'essai prolonge la même logique : il se déploie sur le poste client lui-même, sans équipement dédié. L\'instrument crée une paire de liens virtuels, dite veth, à l\'intérieur du poste. Sur le premier saut, un module du noyau Linux, netem, applique au trafic sortant le délai, la gigue et le taux de perte du profil visé. La discipline de file testée s\'empile sur ce même point d\'émission, de sorte que le plafond de débit couvre l\'envoi. À l\'autre extrémité de la paire, un serveur léger distribue un objet de 16 Ko et accepte le flux de charge. Le poste est ainsi conduit à échanger à travers un lien dont toutes les propriétés sont contrôlées par l\'expérimentateur.' },
  { fig: { file: 'figR1-topologie', caption: 'Topologie du banc : le poste client rejoue le lien d\'accès, infrastructure intacte' } },
  { p: 'Ce placement répond à la contrainte centrale du stage : aucune interruption du réseau de production n\'était acceptable, et la vérité expérimentale exige des conditions contrôlées. Le banc ne remplace pas la mesure de production ; il garantit que les comparaisons entre disciplines s\'effectuent à conditions strictement identiques, et que chaque événement peut être rejoué. La mesure du lien réel demeure possible à tout moment par l\'audit, et son déploiement sur les sites de l\'institution fait partie des perspectives.' },
  { h2: 'II.1.3 La matrice expérimentale' },
  { p: 'Chaque campagne croise les profils de liens avec les disciplines de file et les contrôles de congestion. Quatre profils sont retenus : la fibre de référence (80 Mbit/s, 20 ms), le cellulaire contraint (20 Mbit/s, 100 ms, gigue 15 ms, 0,5 % de perte), le satellite géostationnaire (5 Mbit/s, 600 ms, 1 % de perte) et une liaison par satellite en orbite basse (100 Mbit/s, 40 ms, gigue marquée). Trois disciplines, pfifo_fast, fq_codel et CAKE, se croisent avec deux contrôles de congestion, CUBIC et BBR. Une répétition par cellule donne une campagne de 6 événements par profil, soit 24 pour la matrice complète des quatre profils ; les campagnes antérieures ont accumulé plusieurs répétitions par cellule et sont agrégées dans les médianes.' },

  { h1: 'II.2 Équations et mesures' },
  { h2: 'II.2.1 Percentiles de latence' },
  { p: 'Toutes les latences sont résumées par percentiles. Le centile p est la plus petite valeur v telle qu\'au moins p pour cent des observations organisées en ordre croissant soient inférieures ou égales à v. La médiane p50 décrit le cas typique ; le p95 décrit les cas défavorables que subissent une requête sur vingt. Pour un échantillon trié de n valeurs x1 à xn, le p95 vaut la valeur de rang ceil(0,95 × n) dans cet ordre. Le mémoire rapporte systématiquement la médiane et le p95 plutôt que la moyenne, car ce sont les requêtes lentes qui décident de la qualité perçue du service.' },
  { h2: 'II.2.2 Le respect d\'échéance' },
  { p: 'Le taux de respect d\'échéance, noté deadline_ok, rapporte le nombre de complétions strictement inférieures à l\'échéance choisie au nombre total de complétions mesurées pendant la fenêtre de charge. Pour n complétions de durées ci et une échéance D, ce taux s\'écrit :' },
  { pNoIndent: 'deadline_ok = 100 × (1 / n) × Σ [ ci < D ]' },
  { p: 'où l\'expression entre crochets vaut 1 si la condition est vraie et 0 sinon, D désigne l\'échéance en millisecondes. Le taux se rapporte à une échéance choisie par l\'opérateur, bornée entre 200 et 5 000 ms côté serveur. Sa valeur devient discriminante quand l\'échéance se situe dans la distribution mesurée : à 220 ms sur le profil cellulaire, les disciplines se séparent nettement, alors qu\'une échéance de 1 000 ms ne serait jamais dépassée par ce banc.' },
  { h2: 'II.2.3 Le QDI, écart p95 moins médiane' },
  { p: 'La régularité du lien se mesure par l\'écart entre le p95 de la latence et sa médiane. Le mémoire le nomme QDI, pour dégradation de délai de queue. Formellement, QDI = p95(rtt) − p50(rtt) sur la fenêtre de charge. Un écart faible signifie que presque toutes les requêtes prennent le même temps : le lien est prévisible, ce qui compte autant pour la supervision que la valeur absolue de latence. La littérature des outils publics de mesure du bufferbloat publie des lectures équivalentes sans lui donner de nom court ; le mémoire garde ce nom court et sa définition est celle de l\'écart de percentiles.' },
  { h2: 'II.2.4 Le score de voix, modèle E simplifié' },
  { p: 'Pour traduire les conditions mesurées en qualité de voix, le mémoire applique le modèle E simplifié de la recommandation G.107 de l\'UIT-T. Le score R s\'étend de 0 à 100 et se décompose en un terme de base soustrait des dégradations de délai, de gigue et de perte. Le délai retenu est l\'aller simple, la moitié de l\'aller-retour mesuré. L\'impairment de délai s\'écrit Id = 0,024 × d + 0,11 × (d − 177,3) pour d supérieur à 177,3 ms, où d est le délai aller en millisecondes : le modèle devient sévère au-delà de ce seuil. La gigue, prise égale à l\'écart p95 moins médiane observé, ajoute un terme linéaire approché de 0,024 par milliseconde, en rappelant que le tampon de dé-jitter absorbe une partie de cette variation. La perte subie p, exprimée en fraction, ajoute une dégradation d\'équipement Ie égale à 30 × ln(1/(1 − p)) pour le codec G.711, soit 0 pour une perte nulle. Le score se lit : R = 93,2 − Id − Ie − Ij, borné entre 0 et 100. Un score supérieur à 80 décrit un appel d\'excellente qualité, sous 50 un appel difficile. Cette version simplifiée s\'applique aux conditions mesurées sans flux de référence dédié ; la méthode est celle du cadre UIT, les flux de référence restent une perspective.' },
  { h2: 'II.2.5 Le coût du gaspillage' },
  { p: 'Le gaspillage est estimé à partir des pertes mesurées à la discipline de file : chaque paquet écarté correspond à un segment d\'environ 1 448 octets retransmis par l\'émetteur. La formule du coût rapporte ce volume au prix du gigaoctet du forfait souscrit, puis extrapole la fenêtre d\'événement de trois minutes à l\'heure : coût horaire = (octets gaspillés ÷ 2^30) × (ariary par gigaoctet) × 20. Le prix au gigaoctet n\'est pas une constante : il dépend du forfait souscrit, de 1 000 ariary par gigaoctet pour le forfait journalier à 490 ariary pour la fibre d\'entrée de gamme, d\'après les tarifs publiés en 2026. La mesure expose ce choix de palier plutôt que d\'imposer une constante ; le palier mensuel de 4,5 Go sert de défaut, cohérent avec les liens cellulaires de l\'institution.' },
  { table: {
    id: 'paliers',
    caption: 'Paliers tarifaires observés en 2026 et prix du gigaoctet',
    widths: [34, 22, 22, 26],
    header: ['Forfait', 'Volume', 'Prix (Ar)', 'Ar / Go'],
    rows: [
      ['Yas Ye\'low One (24 h)', '1 Go', '1 000', '1 000'],
      ['Yas Net Month 4,5 Go (30 j)', '4,5 Go', '25 000', '5 556'],
      ['Airtel Net M\'Lay 4,5 Go', '4,5 Go', '25 000', '5 556'],
      ['Yas Net Month 100 Go', '100 Go', '200 000', '2 000'],
      ['Yas Fibre IN 100 Go (FTTH)', '100 Go/mois', '49 000', '490'],
    ] } },
  { p: 'Le forfait mensuel de 4,5 gigaoctets, retenu comme palier par défaut du calcul, présente le pire rapport du catalogue de l\'opérateur principal : le forfait journalier d\'un gigaoctet coûte par gigaoctet plus de cinq fois moins. Ce renversement, documenté sur les grilles publiées en 2026, justifie à lui seul que le palier soit un paramètre du calcul et non une constante.' },
  { h2: 'II.2.4 L\'empreinte de preuve' },
  { p: 'La chaîne de preuve repose sur une fonction de hachage cryptographique. Pour chaque fichier gelé, l\'empreinte SHA-256 est calculée par la formule standard : l\'entrée est traitée par blocs de 512 bits à travers soixante-quatre tours de compression, et l\'empreinte finale est une valeur de 256 bits dont toute modification d\'un octet d\'entrée change la sortie. Le manifeste d\'une campagne enregistre l\'empreinte de chaque fichier ; une commande de vérification recalcule ces empreintes et signale toute divergence. La probabilité qu\'une modification passe inaperçue est négligeable, ce qui donne à chaque tableau du mémoire une vérification indépendante.' },

  { h1: 'II.3 Protocole des campagnes' },
  { h2: 'II.3.1 Le protocole par événement' },
  { p: 'Chaque événement mesure une cellule de la matrice : un profil de lien, une discipline de file, un contrôle de congestion, une répétition. Le protocole impose trois fenêtres fixes. Trente secondes de repos d\'abord : le lien porte les sondes sans charge, la stabilité de cette référence est vérifiée. Cent vingt secondes de charge : un flux TCP massif sature le lien dans le sens montant pendant que les sondes continuent. Trente secondes de récupération : la charge s\'arrête, on observe le retour à l\'état de repos. Trois minutes par événement, environ dix-huit minutes pour six cellules.' },
  { table: {
    id: 'phases',
    caption: 'Déroulement d\'un événement de mesure',
    widths: [20, 15, 65],
    header: ['Phase', 'Durée', 'Contenu'],
    rows: [
      ['Baseline', '30 s', 'Sondes ping et petits objets, aucune charge ; vérification de la stabilité G6'],
      ['Charge', '120 s', 'Flux bulk saturant + sondes critiques poursuivies, mesures publiées à chaque tour'],
      ['Récupération', '30 s', 'Arrêt de la charge, observation du retour à l\'état de repos'],
    ] } },
  { h2: 'II.3.2 Les huit portes de qualité' },
  { p: 'Chaque événement est contrôlé par huit portes évaluées dans l\'ordre du déroulement. La porte G0 exige que la cible réponde aux pings. La porte G1 vérifie que le flux de masse a réellement démarré, sans quoi l\'événement ne mesure rien. La porte G2 exige que les sondes produisent des données pendant la charge. La porte G3 contrôle la plausibilité physique de la latence mesurée. La porte G4 compare le débit mesuré à la capacité du profil : un débit inférieur à la moitié de la capacité déclasse l\'événement. La porte G5 rejette toute ligne dupliquée. La porte G6 vérifie la stabilité de la mesure de repos, condition d\'une comparaison loyale. La porte G7 vérifie que le processeur n\'était pas saturé, une machine occupée faussant toute mesure de latence.' },
  { table: {
    id: 'portes',
    caption: 'Portes de qualité et conséquence d\'échec',
    widths: [10, 55, 35],
    header: ['Porte', 'Condition vérifiée', 'Conséquence d\'échec'],
    rows: [
      ['G0', 'La cible répond aux pings', 'Événement invalidé'],
      ['G1', 'Le flux de masse a démarré', 'Événement invalidé'],
      ['G2', 'Les sondes produisent des valeurs', 'Événement dégradé'],
      ['G3', 'Latence mesurée physiquement plausible', 'Événement invalidé'],
      ['G4', 'Débit cohérent avec la capacité du profil', 'Événement invalidé'],
      ['G5', 'Aucune ligne dupliquée dans le gel', 'Événement invalidé'],
      ['G6', 'Baseline stable avant charge', 'Événement dégradé'],
      ['G7', 'Processeur non saturé', 'Covariable, G7 seul ne rejette pas'],
    ] } },
  { p: 'Un événement qui franchit toutes les portes majeures est gelé au statut valid. Une porte secondaire manquante le rend degraded. Une porte majeure en échec l\'invalidé : sa ligne est écrite, comptée dans le journal de quarantaine, et exclue du classement. Ce traitement honnête des échecs est une exigence de reproductibilité : les comptes sont publiés tels quels.' },
  { h2: 'II.3.2 L\'algorithme de campagne' },
  { p: 'L\'orchestration suit un algorithme en trois niveaux. Au niveau de la campagne, la matrice énumère les cellules : pour chaque profil choisi, pour chaque discipline de file, pour chaque contrôle de congestion, pour chaque répétition, un événement est exécuté. La reprise après interruption est native : les événements déjà gelés sont identifiés par leur paire run et numéro d\'événement et sautés. Au niveau de l\'événement, l\'algorithme installe d\'abord les deux sauts : netem à la racine de l\'émission avec les conditions du profil, puis la discipline de file testée empilée en enfant, après une suppression propre des restes éventuels. Il collecte ensuite les sondes pendant chaque phase et publie les valeurs courantes à chaque tour, pour que la diffusion temps réel porte la vérité de la mesure en cours et pas seulement les frontières de phases. À la fin, les portes clôturent la cellule et la ligne est écrite.' },
  { fig: { file: 'figR1-topologie', caption: 'Topologie du banc : poste client, lien d\'accès reconstitué, serveur de test' } },

  { h1: 'II.5 Matériels' },
  { table: {
    id: 'materiel',
    caption: 'Matériels et environnements',
    widths: [30, 70],
    header: ['Élément', 'Caractéristique'],
    rows: [
      ['Hôte d\'expérimentation', 'PC Windows 10/11, 8 Go de RAM, VMware Workstation ou VirtualBox'],
      ['Machine virtuelle', 'Ubuntu Server 24.04 LTS, noyau 6.x, 2 vCPU, 4 à 5 Go de mémoire'],
      ['Banc réseau', 'paire veth locale, netem (délai, gigue, perte) + discipline de file sur l\'émission'],
      ['Binaire', 'Go statique, frontend React embarqué, aucune dépendance d\'exécution'],
      ['Mesure', 'ping ICMP, HTTP objet 16 Ko, flux TCP de charge, compteurs tc'],
    ] } },
  { p: 'Le banc complet tient sur le poste client : aucune dépendance externe, aucun service distant. La discipline de file et les conditions du lien sont les variables contrôlées de l\'expérimentation, la machine est une covariable surveillée par la porte G7.' },

];
