// Partie IV : L'observatoire CGO, conception et outils.
module.exports = [
  { h1: `PARTIE IV : L'OBSERVATOIRE CGO, CONCEPTION ET OUTILS` },

  { p: `Cette partie présente la solution qui referme l'écart identifié par l'analyse de l'existant. Elle expose d'abord la solution proposée et son architecture générale. Elle compare ensuite, fonction par fonction, les outils disponibles pour composer l'instrument, selon les six critères retenus. Elle présente alors l'outil retenu, l'observatoire CGO, dans son architecture logicielle, ses fonctionnalités, ses avantages et ses limites. Elle expose enfin les fondements théoriques que l'instrument mobilise, dans l'ordre où ils interviennent dans le protocole de mesure.` },

  // ================================================================ 1. Solution proposée
  { h2: `Solution proposée : l'observatoire à vérité terrain CGO` },
  { p: `L'analyse de l'existant a établi un écart : le terrain malgache est un lien hautement contraint, l'état de l'art mesure ces liens sans vérité terrain, et le banc expérimental fournit une vérité terrain par construction. La solution proposée est un instrument qui referme cet écart : l'observatoire CGO (Congestion Ground-truth Observatory).` },
  { p: `CGO est un binaire Go statique d'environ 13 Mo qui, sur une machine unique et sans connexion Internet, exécute les fonctions suivantes. Premièrement, il rejoue des baisses de capacité programmées sur un lien façonné par le noyau, avec un horodatage de vérité terrain connu par construction. Deuxièmement, il lit à 10 Hz les compteurs exacts de la file d'attente via l'interface tc -s du noyau, ce qui permet de dater le début réel de chaque événement de congestion. Troisièmement, il confronte cinq détecteurs de congestion à ces événements datés et produit une archive gelée, hachée par SHA-256 et régénérable par un tiers.` },
  { p: `La solution répond point par point aux trois questions de recherche. RQ1 (détection) est traitée par l'expérience E1, qui compare les cinq détecteurs sur des scénarios dont le début de congestion est connu. RQ2 (estimation) est traitée par l'expérience E2, qui valide les sondes actives contre l'oracle. RQ3 (atténuation) est traitée par l'expérience E3, qui compare un façonneur adaptatif aux configurations statiques d'AQM.` },
  { p: `L'architecture en couches de CGO, que la {figRef:archi} présente, détermine la fiabilité des mesures. La couche présentation et API expose les points de terminaison HTTP pour la configuration, le réglage des paramètres et la récupération des preuves. La couche de contrôle implémente la boucle de rétroaction adaptative et l'évaluation des politiques. La couche d'intégration du plan de données interagit avec le noyau via netlink pour instaurer les disciplines de file et les règles de façonnage. La couche d'observabilité collecte les métriques TCP et les signaux temporels. La couche d'expérimentation orchestre les campagnes reproductibles avec injection de fautes et réconciliation d'environnement.` },
  { fig: { id: 'archi', file: 'fig07-archi', caption: `Architecture de l'observatoire CGO : espaces de noms, goulot façonné, canaux d'observation, archive et console embarquée.` } },
  { p: `L'organisation du code source reflète cette séparation des responsabilités. Le point d'entrée se trouve dans cmd/main_api_first.go. La couche API est assurée par pkg/api/server_v2.go. Le contrôle adaptatif central repose sur pkg/adaptive/controller.go. La configuration est gérée par pkg/config/loader.go. L'intégration noyau pour le façonnage de trafic est réalisée par pkg/qdisc/netlink_manager.go et pkg/shaper/shaper.go. Les campagnes expérimentales sont orchestrées par pkg/campaign/engine.go. La collecte de métriques et les signaux TCP sont pris en charge par pkg/metrics/collector_v2.go. La détection, l'estimation et les statistiques sont réparties dans pkg/detect, pkg/estimate et pkg/stats. Les vérifications d'environnement, l'injection de fautes et les utilitaires de banc d'essai sont assurés par pkg/oracle, pkg/fault et pkg/testbed.` },
  { p: `Chaque nombre publié est vérifiable par un tiers. Les données brutes (captures tcpdump, journaux d'oracle, séries temporelles de chaque détecteur) sont archivées dans un format ouvert avec leur empreinte SHA-256. Le dépôt Zenodo [53] garantit la pérennité de l'archive. Un script de régénération permet à tout chercheur de re-dériver chaque figure et chaque nombre du mémoire à partir de l'archive gelée. Cette propriété de vérifiabilité complète est la raison d'être de l'instrument. Les sections suivantes justifient le choix de chaque outil qui compose la solution, puis exposent les fondements théoriques nécessaires à sa compréhension.` },

  // ================================================================ 2. Comparaison des outils
  { h2: `Comparaison des outils disponibles` },
  { p: `La solution est un instrument composé : chaque fonction (émulation de lien, génération de trafic, mesure du RTT, capture, analyse statistique, rendu des figures, terminal et service) fait l'objet d'une comparaison. Les cinq critères du modèle d'analyse sont appliqués : disponibilité, fiabilité, popularité, besoin en ressources, communauté. Un sixième critère, la vérifiabilité, est ajouté : il mesure la capacité de l'outil à produire une sortie déterministe, régénérable et hachable sans dépendance externe.` },

  { h3: `Émulation de lien` },
  { p: `Trois approches existent pour reproduire les caractéristiques d'un lien contraint : le couple netem et TBF du noyau Linux, l'émulateur en espace utilisateur mahimahi [59], et le simulateur à événements discrets ns-3 [60].` },
  { p: `netem et TBF sont intégrés au noyau Linux et ne nécessitent aucune installation [49][50]. Ils sont utilisés par la quasi-totalité des études AQM publiées dans les conférences PAM et IMC. Leur fiabilité est celle du code noyau, éprouvée par des années d'utilisation. Leur principal avantage pour ce projet est la vérifiabilité : les compteurs de file sont lisibles via tc -s, ce qui donne accès à une vérité terrain que ni mahimahi ni ns-3 ne fournissent directement.` },
  { p: `mahimahi [59] est un émulateur en espace utilisateur qui isole chaque lien dans un conteneur léger. Il a été utilisé dans des études de qualité vidéo, mais sa maintenance a ralenti. ns-3 [60] est un simulateur complet très utilisé dans le monde académique, mais il fonctionne en simulation discrète, pas en émulation noyau : la vérité terrain y est simulée, pas lue dans les compteurs réels. Le {tabRef:outilEmu} résume la comparaison.` },
  { table: {
      id: 'outilEmu',
      caption: `Comparaison des outils d'émulation de lien.`,
      header: ['Critère', 'netem + TBF (noyau)', 'mahimahi', 'ns-3'],
      rows: [
        ['Disponibilité', 'Intégré au noyau, aucune installation [49][50]', 'Libre (MIT) [59]', 'Libre (GPL) [60]'],
        ['Fiabilité', 'Code noyau en C, éprouvé par la recherche AQM', 'C++, isolation par espaces de noms', 'C++, complet, apprentissage long'],
        ['Popularité', 'Standard des études AQM (utilisé par flent)', 'Modérée', 'Très élevée (académique)'],
        ['Ressources', 'Nul (noyau)', 'Faible', 'Élevé (simulation discrète)'],
        ['Communauté', 'Noyau Linux, très active', 'Maintenance ralentie', 'Très active'],
        ['Vérifiabilité', 'Compteurs noyau exacts (tc -s)', 'Compteurs espace utilisateur', 'Vérité simulée, non noyau'],
        ['Verdict', 'RETENU', 'Non requis', 'Non retenu (lourd, vérité simulée)'],
      ],
      widths: [16, 32, 26, 26],
  } },
  { p: `Le verdict est clair : netem et TBF sont retenus comme solution d'émulation principale, parce qu'ils offrent la vérité terrain la plus directe. Les compteurs noyau sont lisibles sans instrumentation supplémentaire. L'interface de gestion des disciplines de file réside dans pkg/qdisc/netlink_manager.go, qui interagit avec le noyau via netlink pour installer, mettre à jour et interroger les qdisc. Le paquet pkg/shaper/shaper.go encapsule les politiques de façonnage et réconcilie l'état désiré avec l'état réel du noyau. Cette séparation entre la mécanique noyau et la politique permet de changer de stratégie de façonnage sans modifier le code d'interaction noyau.` },

  { h3: `Génération de trafic` },
  { p: `Le trafic de charge peut être produit de trois manières : par le rythme d'émission du noyau (BBR ou CUBIC avec l'option de rythme maximal), par iperf3 en espace utilisateur [48], ou par un limiteur à jeton écrit en espace utilisateur.` },
  { p: `Le rythme noyau présente deux avantages décisifs. Premièrement, il évite les artefacts d'ordonnancement de l'espace utilisateur, qui peuvent introduire de la gigue dans le flux de paquets. Deuxièmement, il est entièrement déterministe : le débit imposé par le noyau est reproductible d'une exécution à l'autre. BBR [35] fonde son rythme sur un modèle de bande passante de goulot et de temps de propagation. CUBIC [36][37] augmente la fenêtre de congestion selon une fonction cubique du temps. Les deux sont accessibles comme générateurs de charge par le réglage du contrôle de congestion par socket.` },
  { p: `iperf3 n'est pas écarté, mais conservé comme instrument tiers de réconciliation : le pipeline interne de CGO lui est comparé pour vérifier qu'aucun artefact de mesure n'a été introduit. Ce principe de double canal, où un instrument indépendant que l'expérimentateur n'a pas écrit sert de référence croisée, est un élément central de la méthode de validation. Le {tabRef:outilTrafic} résume la comparaison.` },
  { table: {
      id: 'outilTrafic',
      caption: `Comparaison des générateurs de trafic.`,
      header: ['Critère', 'Rythme noyau (BBR/CUBIC)', 'iperf3', 'Jeton espace utilisateur'],
      rows: [
        ['Disponibilité', 'Intégré au noyau', 'Libre (BSD) [48]', 'Ad hoc, à écrire'],
        ['Fiabilité', 'Rythme noyau, sans artefact', 'Espace utilisateur (artefacts possibles)', 'Dépend de l\u2019implémentation'],
        ['Popularité', 'Standard du contrôle de congestion', 'Très élevée', 'Faible'],
        ['Ressources', 'Nul', 'Faible', 'Faible'],
        ['Communauté', 'Noyau Linux', 'Active (ESnet)', 'Aucune'],
        ['Vérifiabilité', 'Rythme reproductible', 'Rythme moins stable', 'Artefacts d\u2019ordonnancement'],
        ['Verdict', 'RETENU (principal)', 'RETENU (réconciliation)', 'Non retenu'],
      ],
      widths: [16, 30, 28, 26],
  } },
  { p: `La réconciliation avec iperf3 s'effectue en deux temps. Pendant l'expérience, iperf3 mesure le débit du côté récepteur. Après l'expérience, le pipeline interne de CGO calcule le même débit à partir des compteurs de l'oracle et des captures tcpdump. Les trois valeurs sont comparées : si l'écart entre l'oracle et iperf3 dépasse 1 %, la mesure est marquée comme suspecte et l'expérience est rejouée.` },

  { h3: `Mesure du RTT` },
  { p: `Le canal indépendant de mesure du RTT peut être un ping horodaté par le noyau (ping -D), hping [75], ou une sonde maison écrite spécifiquement pour le projet. ping -D [74] est présent sur toutes les distributions Linux, il utilise l'horodatage noyau et ne nécessite aucun privilège particulier. C'est un instrument que l'expérimentateur n'a pas écrit, ce qui garantit son indépendance : si les résultats de l'oracle et ceux du ping concordent, la probabilité d'une erreur systématique dans les deux chaînes de mesure est faible. Le {tabRef:outilRtt} résume la comparaison.` },
  { table: {
      id: 'outilRtt',
      caption: `Comparaison des outils de mesure du RTT.`,
      header: ['Critère', 'ping -D (iputils)', 'hping', 'Sonde maison'],
      rows: [
        ['Disponibilité', 'Libre, présent partout [74]', 'Libre [75]', 'À écrire'],
        ['Fiabilité', 'Horodatage noyau, précis', 'Horodatage espace utilisateur', 'À valider'],
        ['Popularité', 'Universelle', 'Modérée', 'Nulle'],
        ['Vérifiabilité', 'Canal indépendant (non écrit par l\u2019expérimentateur)', 'Moins précis', 'Perte de l\u2019indépendance'],
        ['Verdict', 'RETENU', 'Non retenu', 'Non retenu'],
      ],
      widths: [18, 34, 26, 22],
  } },
  { p: `La fréquence du ping est fixée à 5 Hz, ce qui représente un compromis entre la résolution temporelle et la charge induite sur le lien. Un ping toutes les 200 ms ajoute environ 0,4 kbit/s de trafic pour des paquets de 64 octets, soit 0,0008 % du débit nominal de 50 Mbit/s. Cette charge est négligeable et ne perturbe pas les mesures.` },

  { h3: `Capture` },
  { p: `La capture des paquets est confiée à tcpdump et tshark [52]. Ces deux outils sont scriptables, reproductibles et largement utilisés dans la communauté de mesure réseau. Wireshark [58], son interface graphique, n'est pas retenu : il n'est pas scriptable et ne peut donc pas être intégré dans une chaîne de traitement automatisée.` },
  { p: `Les captures sont déclenchées par le protocole de mesure au début de chaque séquence expérimentale. Les fichiers pcap sont archivés comme preuve brute, avec leur somme SHA-256 dans le manifeste. Un script de post-traitement extrait les métriques nécessaires (RTT par paquet, taux de perte, temps inter-arrivées) sans modifier les fichiers originaux.` },

  { h3: `Analyse statistique` },
  { p: `Les tests statistiques requis par le protocole de validation sont les suivants : test de Wilcoxon signé pour les comparaisons appariées, bootstrap à graine fixée pour les intervalles de confiance, intervalles de Clopper-Pearson pour les proportions, correction de Holm pour les comparaisons multiples, test de Kolmogorov-Smirnov analytique pour la détection de changement de distribution, et test t apparié pour les grandes séries. Chacun peut être implémenté dans une bibliothèque interne en Go, ou confié à R [61] ou SciPy [62].` },
  { p: `Le choix d'une bibliothèque interne se justifie par deux contraintes du projet : le fonctionnement hors ligne (mode avion pendant les campagnes et à la soutenance) et le déterminisme complet (graine fixée, re-pointage identique sur toute machine). R et SciPy sont des environnements fiables et populaires, mais ils exigent une installation séparée et ne garantissent pas le déterminisme inter-plateforme. Le {tabRef:outilStats} résume la comparaison.` },
  { table: {
      id: 'outilStats',
      caption: `Comparaison des outils statistiques.`,
      header: ['Critère', 'pkg/stats (interne, Go)', 'R', 'SciPy'],
      rows: [
        ['Disponibilité', 'Embarqué dans le binaire [55]', 'Libre [61]', 'Libre [62]'],
        ['Fiabilité', 'Tests validés contre les valeurs publiées', 'Très fiable', 'Très fiable'],
        ['Popularité', 'Ad hoc', 'Très élevée', 'Très élevée'],
        ['Ressources', 'Nul (embarqué)', 'Environnement R', 'Python et dépendances'],
        ['Communauté', 'Maintenue par le projet', 'Très active', 'Très active'],
        ['Vérifiabilité', 'Graine fixée, déterministe, hors ligne', 'Environnement externe requis', 'Environnement externe requis'],
        ['Verdict', 'RETENU', 'Non retenu', 'Non retenu'],
      ],
      widths: [16, 32, 26, 26],
  } },
  { p: `La bibliothèque pkg/stats de CGO embarque des tests plus spécialisés que la simple implémentation des tests classiques. Elle intègre des méthodes d'inférence bayésienne, d'analyse de variance (ANOVA), de corrélation, de régression et de méthodes bootstrap. Ces outils permettent d'analyser les résultats des campagnes E1, E2 et E3 selon plusieurs cadres statistiques, ce qui renforce la robustesse des conclusions.` },

  { h3: `Rendu des figures` },
  { p: `Les figures peuvent être produites par gonum/plot et svgo en Go [63][64], par matplotlib en Python [65], ou par Observable Plot et Vega-Lite en JavaScript [66][67]. Le rendu Go produit des SVG déterministes qui peuvent être embarqués dans le binaire lui-même grâce à la directive go:embed [69]. La commande make figures reconstruit chaque figure du mémoire depuis l'archive gelée, sans Python ni navigateur. matplotlib est conservé comme option pour les figures d'annexe, sans être sur le chemin critique. Le {tabRef:outilFig} résume la comparaison.` },
  { table: {
      id: 'outilFig',
      caption: `Comparaison des outils de rendu des figures.`,
      header: ['Critère', 'gonum/plot + svgo (Go)', 'matplotlib', 'Observable Plot / Vega-Lite'],
      rows: [
        ['Disponibilité', 'Libre [63][64]', 'Libre [65]', 'Libre [66][67]'],
        ['Fiabilité', 'Sortie SVG vectorielle', 'Très fiable (PNG, PDF)', 'Exige un navigateur'],
        ['Popularité', 'Modérée (gonum)', 'Très élevée', 'Élevée'],
        ['Ressources', 'Nul (embarqué)', 'Python et dépendances', 'Node ou navigateur'],
        ['Communauté', 'Active', 'Très active', 'Active'],
        ['Vérifiabilité', 'SVG déterministe, hachable, hors ligne', 'Environnement externe', 'Non hors ligne'],
        ['Verdict', 'RETENU', 'Optionnel (annexes)', 'Non retenu'],
      ],
      widths: [16, 30, 26, 28],
  } },

  { h3: `Terminal et service` },
  { p: `L'interface embarquée de CGO repose sur xterm.js [68] pour le terminal et sur le serveur HTTP du langage Go avec go:embed [69] pour servir l'interface depuis le binaire unique. xterm.js est le standard de fait des terminaux dans le navigateur. Les ressources statiques (HTML, CSS, JavaScript) sont compilées dans le binaire via go:embed, ce qui garantit que l'ensemble du dispositif tient dans un seul fichier exécutable.` },
  { p: `Les tableaux de bord généralistes Grafana [70], netdata [71], Zabbix [72] et Nagios [73] ne sont pas retenus. Ce sont des piles serveurs complètes, non embarquables dans un binaire statique de 13 Mo. Surtout, ils mesurent la disponibilité d'une infrastructure, pas la congestion contre une vérité terrain. Les vues scientifiques dont le projet a besoin (ECDF de délais de détection, raster aligné sur les événements, comparaison oracle-sonde) ne sont pas disponibles dans ces outils. flent [43][44] et les outils de bufferbloat.net [57] ne sont pas des candidats à l'implémentation mais des comparateurs méthodologiques : leur rôle est de situer l'apport de CGO dans l'état de l'art.` },
  { p: `Le choix de xterm.js plutôt qu'un terminal natif se justifie par une raison pratique : le binaire unique doit fonctionner en mode avion, sans installation. Un terminal dans le navigateur, servi par le binaire lui-même, évite toute dépendance extérieure. L'utilisateur ouvre un navigateur, pointe sur l'adresse locale du serveur HTTP de CGO, et accède à la console, à l'explorateur d'archive et au vérifieur.` },

  { h3: `Synthèse des choix d'outils` },
  { table: {
      id: 'outilSynth',
      caption: `Synthèse des choix d'outils.`,
      header: ['Fonction', 'Outil retenu', 'Justification dominante'],
      rows: [
        ['Émulation de lien', 'netem + TBF (noyau)', 'Vérité terrain lisible dans les compteurs noyau'],
        ['Génération de trafic', 'Rythme noyau (BBR/CUBIC)', 'Absence d\u2019artefacts espace utilisateur'],
        ['Mesure du RTT', 'ping -D', 'Horodatage noyau, canal indépendant'],
        ['Capture', 'tcpdump + tshark', 'Scriptable, reproductible'],
        ['Analyse statistique', 'pkg/stats (Go)', 'Déterminisme à graine fixée, hors ligne'],
        ['Rendu des figures', 'gonum/plot + svgo', 'SVG déterministe, hachable, embarqué'],
        ['Terminal', 'xterm.js', 'Standard de fait, embarquable'],
        ['Service et intégration', 'Go net/http + go:embed', 'Binaire unique, mode avion'],
      ],
      widths: [24, 30, 46],
  } },
  { p: `Le {tabRef:outilSynth} résume l'ensemble des choix. Chaque outil retenu satisfait le critère de vérifiabilité : une sortie déterministe, régénérable et hachable sans dépendance externe. Ce critère s'est révélé le plus discriminant de la comparaison : il a écarté des outils pourtant fiables et populaires (R, SciPy, matplotlib en chemin critique) parce qu'ils ne pouvaient pas être embarqués dans le binaire unique ni fonctionner hors ligne.` },

  // ================================================================ 3. Présentation de l'outil retenu
  { h2: `Présentation de l'outil retenu : CGO` },

  { h3: `Architecture logicielle et organisation des paquets` },
  { p: `CGO est un observatoire de congestion à vérité terrain. C'est un exécutable Go statique (ELF, environ 13 Mo, ressources embarquées à la compilation) qui fonctionne sur une machine virtuelle unique. La VM cible est Ubuntu 24.04 LTS, noyau 6.8, 2 vCPU, 4 Go de RAM, au moins 40 Go de disque. Il ne dépend d'aucun service externe : l'accès à Internet n'est requis qu'en phase de préparation.` },
  { p: `Le point d'entrée cmd/main_api_first.go initialise le serveur HTTP, charge la configuration et démarre la boucle de contrôle adaptative. Le paquet pkg/config/loader.go charge et valide la configuration depuis des fichiers et des variables d'environnement, en fournissant des valeurs par défaut et un accès typé. Le paquet pkg/api/server_v2.go expose les points de terminaison HTTP pour l'application de la configuration, le réglage des paramètres, la récupération des preuves et les sondes en direct.` },
  { p: `Le cœur du système réside dans pkg/adaptive/controller.go. Ce contrôleur implémente la boucle de rétroaction adaptative : il reçoit les métriques et les événements du pipeline d'observabilité, évalue les politiques et les règles, calcule les ajustements du débit d'émission, et émet les décisions vers le sous-système de façonnage de trafic. Ses méthodes principales sont UpdateParameters, Observe, ComputeAdjustment, ApplyPolicy et LogDecision. Les règles de politique sont encapsulées dans le type PolicyRule, dont la méthode Evaluate retourne un booléen et GetAction retourne l'action à entreprendre.` },
  { p: `Le contrôleur adaptatif intègre un module ARMS qui implémente une logique de bandit manchot pour sélectionner la meilleure stratégie de contrôle en fonction des conditions observées. Ce module explore et exploite simultanément les configurations possibles, en attribuant un score de performance à chaque stratégie et en orientant la sélection vers celle qui maximise le débit utile tout en minimisant le délai de file. L'intégration du bandit dans la boucle de contrôle permet à CGO de s'adapter automatiquement aux changements de profil de lien sans intervention humaine.` },
  { p: `L'instrument construit deux espaces de noms réseau [51] reliés par une paire veth dont l'interface thesis-veth0 est le goulot. Ce goulot est façonné par netem [49] pour le délai, TBF [50] pour la limitation de débit, et une discipline de file (fq_codel par défaut) pour la gestion active de l'attente. Les offloads matériels sont désactivés sur cette interface. La collecte de métriques est assurée par pkg/metrics/collector_v2.go, qui rassemble les informations TCP via /proc/net/tcp et les interfaces du noyau, calcule les statistiques de délai, de perte et de bande passante, et les diffuse vers le contrôleur adaptatif. Le moteur de campagne pkg/campaign/engine.go orchestre les expériences selon un cycle en quatre phases : initialisation de l'environnement, exécution des phases de test avec fautes contrôlées, collecte des preuves et des artefacts, et génération des rapports.` },
  { p: `Le serveur HTTP embarqué propose trois vues, dont la {figRef:console} présente la première. La console donne accès au parcours de l'observatoire (détection, traitement, résultat, validation) et au flux de l'oracle à 10 Hz, avec un terminal dans le navigateur servi par xterm.js [68]. L'explorateur d'archive permet de naviguer dans les résultats des campagnes et d'afficher les figures régénérées. Le vérifieur compare les sommes SHA-256 courantes aux valeurs du manifeste et signale toute altération.` },
  { fig: { id: 'console', file: 'fig17-console', caption: `Capture de la console CGO dans le navigateur : parcours de l'observatoire, flux de l'oracle noyau à 10 Hz et indicateurs d'intégrité SHA-256.`, screenshot: true } },
  { p: `La {figRef:dashboard} présente la vue d'ensemble de la console, qui regroupe l'état du goulot, la bande passante instantanée et les alertes de détection. La {figRef:replay2} illustre la relecture d'une séquence E1 : série de RTT, fenêtre de détection et délai confirmé par l'oracle. Le {figRef:audit} compare les sommes SHA-256 courantes au manifeste de la campagne. L'{figRef:preuves} montre l'explorateur d'archive et le paquet de preuves d'un événement. Enfin, le {figRef:decisions} affiche le journal des décisions du contrôleur adaptatif. Ces captures seront remplacées par les copies d'écran définitives de la console.` },
  { fig: { id: 'dashboard', file: 'fig18-tableau-de-bord', caption: `Vue d'ensemble de la console CGO : état du goulot, bande passante instantanée et alertes de détection.`, screenshot: true } },
  { fig: { id: 'replay2', file: 'fig19-replay', caption: `Relecture d'une séquence E1 dans la console CGO : série de RTT, fenêtre de détection et délai confirmé par l'oracle.`, screenshot: true } },
  { fig: { id: 'audit', file: 'fig20-audit', caption: `Vérifieur d'intégrité de CGO : comparaison des sommes SHA-256 courantes aux valeurs du manifeste.`, screenshot: true } },
  { fig: { id: 'preuves', file: 'fig21-preuves', caption: `Explorateur d'archive de CGO : paquet de preuves d'un événement (captures tcpdump, journaux d'oracle, décisions).`, screenshot: true } },
  { fig: { id: 'decisions', file: 'fig22-decisions', caption: `Journal des décisions du contrôleur adaptatif : condition, raison et résultat horodatés.`, screenshot: true } },

  { h3: `Fonctionnalités détaillées` },
  { p: `L'outil expose les fonctions suivantes. L'ordonnancement d'événements de congestion produit des variations brusques (échelons), progressives (rampes) et cycliques (effondrements diurnes) de la capacité, avec horodatage de vérité terrain. La lecture de l'oracle noyau à 10 Hz via tc -s class show fournit la taille instantanée de la file, le nombre de paquets transmis et abandonnés, et le débit instantané du goulot.` },
  { p: `Le pointage hors ligne des cinq détecteurs s'effectue par la commande de re-pointage, déterministe et rejouable sur toute machine. Le détecteur à seuil fixe déclenche une alarme lorsque le RTT dépasse une valeur absolue configurable. Le détecteur à gradient réagit à la pente de la série temporelle du RTT. Le détecteur EWMA lisse le signal avec un facteur alpha configurable et compare la valeur lissée à un seuil. Le détecteur z-score sur médiane glissante normalise le RTT courant par rapport à la distribution locale estimée sur une fenêtre de 60 échantillons. Le cinquième détecteur, le test de Kolmogorov-Smirnov à deux échantillons [39], compare des distributions entières de RTT : il réagit à l'élargissement de la distribution avant que la moyenne ne franchisse un seuil, propriété décisive sur les rampes et les effondrements progressifs.` },
  { p: `Les trois expériences E1, E2 et E3 sont exécutées avec leurs scénarios, répétitions et contrôles négatifs. E1 compare les cinq détecteurs sur des scénarios calibrés dont le début de congestion est daté. E2 valide les sondes actives (paire de paquets, train de paquets) contre l'oracle TBF. E3 compare l'atténuation de la congestion par quatre configurations de file : pfifo_fast, fq_codel par défaut, fq_codel réglé et un façonneur adaptatif.` },
  { p: `Les contrôles négatifs (sabotages programmés NC-1, NC-2, NC-3) doivent échouer : si l'un d'eux passe, le protocole de mesure est interrompu et l'expérience est invalide. NC-1 désactive l'épinglage de route : si le trafic contourne le goulot, la file ne se forme pas. NC-2 supprime la discipline de file : en l'absence de fq_codel, le bufferbloat doit être visible et le détecteur de délai de file doit le signaler. NC-3 désactive les offloads : le protocole vérifie que cette condition est remplie avant chaque exécution.` },
  { p: `La chaîne d'intégrité SHA-256 produit un manifeste qui garantit que les données n'ont pas été modifiées. La régénération des figures depuis l'archive gelée s'effectue par une commande unique. Le protocole de validation est conçu pour être exécuté par un tiers : une fois l'archive téléchargée depuis Zenodo [53], le tiers vérifie les sommes, exécute le script de régénération, et compare les figures produites à celles du mémoire. La {figRef:repro} présente cette chaîne de reproductibilité de bout en bout.` },
  { fig: { id: 'repro', file: 'fig16-reproductibilite', caption: `Chaîne de reproductibilité de CGO : de la configuration à graine fixée jusqu'aux figures déterministes, avec vérification par un tiers et chaînage SHA-256.` } },

  { h3: `Avantages et limites` },
  { p: `Le {tabRef:avlim} présente les avantages et les limites de CGO de manière symétrique. Chaque avantage est accompagné d'une limite reconnue, avec la mitigation adoptée.` },
  { table: {
      id: 'avlim',
      caption: `Avantages et limites de CGO.`,
      header: ['Avantages', 'Limites et mitigations'],
      rows: [
        ['Vérité terrain par construction : événements datés, compteurs noyau exacts', 'Émulation : la validité externe repose sur le bras 4G réel, activé par défaut'],
        ['Double canal, contrôles négatifs, chaîne SHA-256 : résultats difficilement falsifiables', 'Machine unique : bruit de VM, mitigé par épinglage processeur, covariable et plans appariés'],
        ['Binaire unique, hors ligne, coût nul en logiciel, ~20 000 Ar de matériel', 'Périmètre : pas d\u2019eBPF ni de multi-machine, renvoyé aux perspectives'],
        ['Reproductibilité complète : make figures, re-pointage, dépôt Zenodo [53]', 'Exécution par un seul candidat, mitigée par points de contrôle et niveau minimal pré-enregistré'],
        ['Ancrage malgache : bras 4G réel prépayé, profils issus de traces locales', 'Bras réel descriptif (n = 15 à 25), sans assertion inférentielle'],
      ],
      widths: [50, 50],
  } },
  { p: `Cinq avantages sont identifiés, chacun avec sa limite. La première limite est la plus importante : CGO fonctionne en émulation, et sa validité externe dépend du bras 4G réel. Aucune assertion inférentielle n'est tirée de ces mesures : elles servent de test de réalité pour vérifier que les résultats d'émulation tiennent sur un lien réel.` },
  { p: `Le point important est que CGO n'est pas un outil de monitoring réseau généraliste. Il ne remplace pas Nagios pour la supervision d'infrastructure, ni Wireshark pour le diagnostic de protocole, ni Grafana pour les tableaux de bord en temps réel. C'est un instrument de mesure scientifique, conçu pour une tâche précise : produire des événements de congestion datés contre lesquels des détecteurs sont comparés.` },

  { h3: `Environnement de bac à sable et réconciliation` },
  { p: `Le paquet pkg/testbed fournit l'environnement de bac à sable dans lequel les expériences sont exécutées. Cet environnement isole chaque campagne dans des espaces de noms Linux dédiés, garantissant que les expériences successives ne s'influencent pas mutuellement. L'isolation est assurée par la création d'espaces de noms réseau, de pid et de montage, ce qui évite les interférences entre le trafic de l'expérience et les processus de la machine hôte.` },
  { p: `La procédure de réconciliation d'environnement vérifie que l'état du système est conforme aux attentes avant chaque exécution. Elle vérifie la présence des modules noyau nécessaires (sch_netem, sch_tbf, sch_fq_codel, cls_u32), la disponibilité des espaces de noms, l'absence de processus résiduels d'une campagne précédente, et la désactivation des offloads matériels sur l'interface de goulot. Si l'une de ces conditions n'est pas remplie, le protocole interrompt la campagne et signale l'anomalie.` },
  { p: `L'injection de fautes est gérée par pkg/fault. Trois types de fautes sont programmés : la perte de paquets (simulée par netem avec un taux configurable), la gigue (variation du délai de propagation) et la panne de lien (suppression temporaire de l'interface de goulot). Chaque faute est horodatée et enregistrée dans le journal d'expérience, ce qui permet de corréler les réactions des détecteurs avec les événements injectés.` },
  { p: `L'oracle, implémenté dans pkg/oracle, est le composant central de vérification. Il lit les compteurs du noyau à 10 Hz, calcule le délai de file instantané, le débit du goulot et le taux de perte, et horodate chaque lecture avec une précision de l'ordre de la milliseconde. Le processus de réconciliation double canal compare les données de l'oracle avec celles du canal indépendant (ping -D pour le RTT, iperf3 pour le débit). Si l'écart entre les deux canaux dépasse le seuil de tolérance (1 % pour le débit, 2 ms pour le RTT médian), l'expérience est marquée comme suspecte et doit être rejouée. Ce seuil a été déterminé empiriquement lors des premières exécutions de calibration, en analysant la distribution des écarts sur des séquences témoins sans congestion.` },

  { h3: `Pipeline de données et visualisation` },
  { p: `Le pipeline de données de CGO transforme les mesures brutes en indicateurs exploitables selon une chaîne en cinq étapes. La capture acquiert les données brutes (tcpdump, compteurs noyau, sondes ping). L'extraction isole les métriques pertinentes (RTT par paquet, débit instantané, taille de file). L'agrégation calcule les statistiques résumées (médiane, P95, écart-type) sur des fenêtres de temps configurables. L'analyse applique les tests statistiques (Wilcoxon, bootstrap, K-S). La visualisation produit les figures SVG par gonum/plot et svgo.` },
  { p: `La visualisation des résultats repose sur quatre types de figures. Les séries temporelles superposent le RTT, le débit et la taille de file sur un même axe temporel, avec les marqueurs d'événements de congestion. Les ECDF comparent les distributions de latence entre configurations. Les rasters alignés superposent les périodes de charge et les détections. Les diagrammes de concordance de Bland et Altman visualisent le biais et les limites de concordance entre canaux.` },
  { p: `Le pipeline est conçu pour être entièrement reproductible. Chaque étape prend son entrée depuis l'archive gelée et produit une sortie déterministe. Les figures sont générées au format SVG vectoriel, ce qui garantit qu'elles s'affichent correctement à toute résolution. Les paramètres de visualisation (fenêtres, couleurs, échelles) sont fixés dans un fichier de configuration unique, ce qui évite les divergences entre figures. L'interface web, servie par go:embed, propose une navigation interactive dans les résultats : l'utilisateur sélectionne une campagne, explore ses séquences, visualise les figures régénérées et télécharge les données brutes. Cette interface est conçue pour être utilisée pendant la soutenance, où le jury peut vérifier en direct que les résultats présentés sont identiques à ceux produits par l'archive.` },

  { h3: `Détail des algorithmes de détection` },
  { p: `Chacun des cinq détecteurs mérite une description précise de son fonctionnement, car les résultats de l'expérience E1 dépendent directement de leurs paramètres. Le détecteur à seuil fixe compare chaque valeur de RTT à un seuil S configurable : si le RTT dépasse S, l'alarme est déclenchée. Ce détecteur est le plus simple et le plus rapide, mais il est aveugle aux variations locales du RTT de base : un seuil adapté à un réseau local sera trop bas pour un lien satellite, et inversement.` },
  { p: `Le détecteur à gradient calcule la pente du RTT par régression linéaire sur une fenêtre glissante de N échantillons. Si la pente dépasse un seuil G, l'alarme est déclenchée. Ce détecteur réagit rapidement aux variations brusques (les échelons) mais peut produire des faux positifs sur une gigue normale. En pratique, N est fixé à 10 échantillons (soit 2 secondes à 5 Hz) et G est calibré sur les phases de calibration.` },
  { p: `Le détecteur EWMA applique un lissage exponentiel à la série temporelle : la valeur lissée à l'instant t vaut alpha fois le RTT courant plus (1 moins alpha) fois la valeur lissée précédente. La valeur lissée est comparée à un seuil. Le facteur alpha, typiquement fixé à 0,125, contrôle le compromis entre réactivité et lissage : un alpha élevé suit les variations rapides mais peut déclencher des alarmes intempestives, un alpha faible lisse les variations mais retarde la détection.` },
  { p: `Le détecteur z-score sur médiane glissante est plus robuste que l'EWMA aux valeurs extrêmes isolées. Il maintient une estimation de la médiane et de l'écart absolu médian (MAD) sur une fenêtre de 60 échantillons. Le z-score est calculé comme l'écart du RTT courant à la médiane, normalisé par le MAD. Si le z-score dépasse un seuil Z (typiquement 3), l'alarme est déclenchée. Ce détecteur s'adapte automatiquement au RTT de base local, ce qui le rend utilisable sur tout type de lien sans recalibration.` },
  { p: `Le détecteur par test de Kolmogorov-Smirnov [39] est le plus sensible aux changements subtils de la distribution du RTT. Il compare l'échantillon courant (60 derniers RTT) à l'échantillon de référence (les 60 RTT précédant la fenêtre courante) par le test K-S à deux échantillons. La statistique D mesure la distance maximale entre les deux fonctions de répartition empiriques. Si D dépasse le seuil calibré, l'alarme est déclenchée. Ce détecteur réagit à l'élargissement de la distribution du RTT, qui précède souvent l'augmentation de la moyenne. Son coût est plus élevé que celui des détecteurs ponctuels, car il nécessite de trier les échantillons ; pour une fenêtre de 60 points, le surcoût est négligeable sur du matériel moderne.` },

  // ================================================================ 4. Fondements théoriques
  { h2: `Fondements théoriques` },

  { h3: `Congestion et bufferbloat` },
  { p: `Lorsqu'un flux sature un goulot, les paquets s'accumulent dans la file d'attente. Tant que la file n'est pas pleine, il n'y a pas de perte, seulement du délai. Les files surdimensionnées produisent des centaines de millisecondes de délai persistant : c'est le bufferbloat, identifié par Gettys et Nichols [34]. L'objectif, formalisé par Nichols et Jacobson [33] puis par la RFC 7567 [32], est de maintenir le délai de file faible sans sacrifier l'utilisation du lien. La mesure pertinente sur un lien contraint est donc la décomposition du temps d'aller-retour entre délai de propagation (fixe, propre à la distance) et délai de file (variable, propre à la charge), que la {figRef:decomp} illustre.` },
  { fig: { id: 'decomp', file: 'fig08-decomposition', caption: `Décomposition du RTT entre délai de propagation et délai de file, avant et après l'application de fq_codel.` } },
  { p: `La mesure du délai de file plutôt que du seul RTT total est une décision méthodologique. Le RTT total varie avec la distance et le routage, ce qui le rend difficile à interpréter seul. Le délai de file, en revanche, ne dépend que de la charge et de la capacité du goulot. C'est la grandeur que les AQM cherchent à contrôler et que les détecteurs doivent estimer. L'oracle de CGO permet de réaliser cette décomposition : les compteurs tc -s fournissent la taille instantanée de la file, que l'on convertit en délai de file en divisant par le débit de service.` },
  { p: `Ce phénomène est particulièrement aigu sur les liens contraints comme ceux observés à Madagascar. Les files d'attente des routeurs 4G peuvent atteindre plusieurs centaines de paquets, accumulant un délai de plusieurs secondes. Ce délai dégrade l'expérience utilisateur bien avant que la perte de paquets ne se produise. La relation fondamentale qui relie le délai de file, la taille de la file et le débit de service est donnée par la formule de Little : le nombre moyen de paquets dans la file est le produit du débit d'arrivée par le temps d'attente moyen. Sur un lien de capacité C, le délai de file maximal vaut la capacité de la file divisée par C. Pour une file de 1 000 paquets de 1 500 octets sur un lien à 5 Mbit/s, le délai de file maximal atteint 2,4 secondes, ce qui rend la navigation web impossible.` },
  { p: `Les mécanismes de contrôle de congestion du noyau Linux interviennent à deux niveaux. Au niveau micro, le contrôle de congestion de la couche transport ajuste la fenêtre d'émission en fonction des pertes et du délai. Au niveau macro, les disciplines de file du noyau gèrent l'ordre et le moment de l'émission des paquets sur l'interface. Les deux niveaux interagissent : le comportement de la qdisc détermine les pertes et le délai que le contrôle de congestion observe.` },

  { h3: `Gestion active de file d'attente` },
  { p: `CoDel [31] contrôle le délai de file en abandonnant les paquets lorsque la file reste au-dessus d'une cible (5 ms par défaut) pendant un intervalle de 100 ms. fq_codel [30] y ajoute une répartition par flux qui évite qu'un flux glouton n'impose son délai aux autres. CAKE [38] intègre le façonnage de débit et la gestion active de file dans une discipline unique, mais n'est pas disponible par défaut sur Ubuntu 24.04.` },
  { p: `L'expérience E3 compare quatre configurations. pfifo_fast, la file simple du noyau, souffre du bufferbloat et sert de référence négative. fq_codel au réglage par défaut du noyau (cible 5 ms, intervalle 100 ms) est la configuration standard. fq_codel avec un réglage optimisé (cible réduite à 2 ms, intervalle adapté à 50 ms) explore l'espace des paramètres. Le façonneur adaptatif, dont le débit est contrôlé par le signal du détecteur, est la configuration candidate. Le {tabRef:qdiscs} synthétise ces quatre disciplines.` },
  { table: {
      id: 'qdiscs',
      caption: `Synthèse des disciplines de file comparées dans l'expérience E3.`,
      header: ['Bras', 'Discipline', 'Paramétrage', 'Rôle dans la comparaison'],
      rows: [
        ['A0', 'pfifo_fast', 'File simple du noyau, sans AQM', 'Référence négative (bufferbloat attendu)'],
        ['A1', 'fq_codel', 'Défaut du noyau : cible 5 ms, intervalle 100 ms', 'Configuration standard'],
        ['A2', 'fq_codel réglé', 'Cible 2 ms, intervalle 50 ms', 'Exploration des paramètres'],
        ['A3', 'Façonneur adaptatif', 'Débit contrôlé par le signal de détection', 'Configuration candidate'],
      ],
      widths: [10, 24, 36, 30],
  } },
  { p: `Les critères de comparaison sont les suivants. Le QDI (Queue Delay Inflation) mesure la dégradation du délai de file par rapport à une référence sans charge. Le TTB mesure le temps nécessaire pour que la file atteigne sa taille maximale après le début de la congestion. Le P95 de latence des petits objets capture le vécu d'un utilisateur qui télécharge une page web ou envoie un message pendant la congestion. L'indicateur VoIP est dérivé du modèle E [42] de l'ITU-T, qui transforme le délai et la perte en un score de qualité perçue.` },
  { p: `La gestion active de file n'est pas une panacée. Sur un lien où le débit varie rapidement (comme le profil 4G entre 5 et 50 Mbit/s), une AQM trop agressive peut abandonner des paquets inutilement pendant les creux de trafic, dégradant le débit utile sans améliorer le délai. L'expérience E3 est conçue pour détecter ce phénomène : si fq_codel réduit le débit utile de plus de 5 % par rapport à pfifo_fast sans améliorer le délai, alors le réglage doit être adapté.` },

  { h3: `Contrôle de congestion` },
  { p: `CUBIC [36][37], fondé sur la perte, est le comportement par défaut de Linux. Il augmente la fenêtre de congestion selon une fonction cubique du temps écoulé depuis la dernière perte, ce qui le rend performant sur les liens à haut produit débit-délai. BBR [35] fonde son rythme sur un modèle de bande passante de goulot et de temps de propagation, sans attendre la perte pour réduire le débit. Le contrôle de congestion est fixé par socket, ce qui permet de comparer le comportement de CUBIC et de BBR sur les mêmes scénarios.` },
  { p: `La comparaison entre CUBIC et BBR est instructive pour le contexte malgache. CUBIC, étant fondé sur la perte, remplit la file jusqu'au débordement avant de réduire son rythme. Sur un lien à haut produit débit-délai comme le profil VSAT, cette attente peut durer plusieurs secondes, pendant lesquelles la file atteint plusieurs mégaoctets. BBR, en modélisant le goulot, évite ce remplissage excessif mais peut sous-estimer la bande passante disponible lorsque le trafic traversant varie rapidement. Ni CUBIC ni BBR n'est un candidat à la solution : ils sont utilisés comme générateurs de charge pour mettre à l'épreuve les détecteurs et les AQM. Le choix de l'algorithme de contrôle de congestion n'est pas l'objet du travail ; l'objet est la méthode de mesure qui permet de les comparer.` },

  { h3: `Détection d'événements de congestion` },
  { p: `Le moteur de détection de CGO repose sur une interface commune qui permet d'ajouter de nouveaux détecteurs sans modifier le reste du système. Chaque détecteur implémente un contrat d'interface avec une méthode Evaluate qui retourne un score ou une alarme. Cette conception permet de comparer les algorithmes sur des bases égales. Le {tabRef:detecteurs} synthétise les cinq détecteurs, leur principe et leur compromis attendu.` },
  { table: {
      id: 'detecteurs',
      caption: `Synthèse des détecteurs d'événements de congestion.`,
      header: ['Détecteur', 'Principe', 'Paramètres clés', 'Compromis attendu'],
      rows: [
        ['Seuil fixe', 'RTT comparé à un seuil absolu', 'Seuil S', 'Simple mais aveugle au RTT de base'],
        ['Gradient', 'Pente locale par régression linéaire', 'Fenêtre N = 10, seuil G', 'Rapide sur échelons, FP sur gigue'],
        ['EWMA', 'Lissage exponentiel puis seuil', 'alpha = 0,125, seuil', 'Peu de FP, détection retardée'],
        ['z-score (BaDDrD)', 'Écart normalisé à la médiane glissante (MAD)', 'Fenêtre 60, seuil Z = 3', 'Auto-adaptatif au lien'],
        ['K-S à deux échantillons', 'Distance entre distributions de RTT', 'Fenêtres 60/60, seuil D calibré', 'Précoce sur rampes, FP plus élevés'],
      ],
      widths: [18, 30, 26, 26],
  } },
  { p: `Les cinq détecteurs couvrent un spectre allant du plus simple au plus sophistiqué. Le seuil de détection du test K-S est calibré sur des données de calibration enregistrées en l'absence de congestion, où les variations du RTT sont uniquement dues au bruit de mesure. Cette calibration préliminaire fixe la valeur de la distance de Kolmogorov-Smirnov au-delà de laquelle l'alarme est déclenchée, ce qui permet de comparer les détecteurs à taux de faux positifs contrôlé.` },

  { h3: `Estimation de bande passante` },
  { p: `Deux méthodes de sondes actives sont validées dans l'expérience E2. La dispersion de paires de paquets envoie deux paquets à la suite et estime la bande passante à partir de l'écart de leurs temps d'arrivée [40]. Le train de paquets envoie une rafale plus longue et estime la bande passante moyenne de la rafale [41].` },
  { p: `Les deux méthodes sont validées contre l'oracle dans un cadrage d'étude de concordance [45]. L'oracle fournit la bande passante réelle du goulot, lue dans les compteurs TBF. Les sondes fournissent une estimation. L'accord entre les deux est quantifié par la méthode de Bland et Altman, qui mesure le biais et les limites de concordance. Cette méthode est choisie parce qu'elle révèle la structure de l'erreur d'estimation : le biais indique si la sonde surestime ou sous-estime systématiquement la bande passante, et les limites de concordance (à 1,96 écart-type) donnent l'intervalle dans lequel 95 % des erreurs se situent. Une sonde qui aurait un biais nul mais des limites de concordance larges serait précise en moyenne mais inutilisable pour une estimation instantanée.` },
  { p: `L'expérience E2 compare les deux méthodes sur les trois types de liens (VSAT, 4G fixe, 4G mobile) et sur une gamme de charges traversantes (0 %, 25 %, 50 %, 75 % du débit nominal). Le protocole prévoit 20 répétitions par condition, ce qui permet de construire des intervalles de confiance sur le biais et les limites de concordance par bootstrap.` },

  { h3: `Métriques et statistiques` },
  { p: `Le choix des méthodes statistiques répond à une contrainte précise : les échantillons de mesures réseau ne sont jamais indépendants au sens strict, car les observations successives sont corrélées dans le temps. Le test de Wilcoxon signé est préféré au test t paramétrique pour les comparaisons appariées, car il ne suppose pas la normalité des résidus et il est robuste aux valeurs extrêmes qui apparaissent dans les mesures de latence.` },
  { p: `Le bootstrap à graine fixée (9 999 réplications) est utilisé pour construire les intervalles de confiance des métriques. La graine fixée garantit que deux exécutions sur des machines différentes produisent les mêmes intervalles : sans cette précaution, deux chercheurs qui exécutent le même script d'analyse sur les mêmes données obtiendraient des intervalles légèrement différents, ce qui rendrait la vérification impossible. Le nombre de 9 999 réplications donne une précision suffisante sur les centiles extrêmes sans allonger excessivement le temps de calcul. Les intervalles de Clopper-Pearson sont utilisés pour les proportions (taux de détection, taux de faux positif), car ils sont conservatifs et valides pour toute taille d'échantillon.` },
  { p: `La correction de Holm est appliquée pour le contrôle de la famille d'hypothèses lorsqu'une même expérience compare plusieurs configurations entre elles, comme c'est le cas dans E3. Le seuil de signification est fixé à 0,05 pour toutes les inférences. Les résultats sont rapportés avec leur intervalle de confiance à 95 %, et non avec une simple p-value, conformément aux recommandations des conférences PAM et IMC. L'analyse de variance à un facteur est utilisée dans E3 pour détecter si les différences de QDI entre les quatre configurations sont statistiquement significatives, et le coefficient de corrélation de Spearman, qui ne suppose pas de relation linéaire, est préféré au coefficient de Pearson pour mesurer les relations entre métriques.` },
  { p: `La qualité d'expérience est mesurée par plusieurs indicateurs complémentaires. Le QDI exprime en millisecondes la dégradation du délai de file par rapport à la référence sans charge. Le TTB exprime en secondes le temps de remplissage de la file. Le P95 de latence des petits objets capture le vécu d'un utilisateur réel. L'indicateur VoIP, dérivé du modèle E [42], convertit le délai et la perte en un score de qualité perçue. Ces indicateurs sont calculés pour chaque configuration et chaque répétition, puis agrégés par les méthodes statistiques décrites ci-dessus. Le script d'analyse est embarqué dans le binaire CGO et s'exécute sur l'archive gelée : tout chercheur qui télécharge le dépôt Zenodo peut reproduire l'intégralité des tests, des figures et des nombres du mémoire, sans installer R, Python ou aucun autre logiciel. Cette propriété n'est pas un luxe : c'est la condition pour qu'un travail de mesure soit falsifiable au sens de Popper.` },

  // ================================================================ Synthèse
  { h2: `Synthèse` },
  { p: `Cette partie a présenté la solution proposée pour répondre à l'écart identifié par l'analyse de l'existant : l'observatoire CGO, un binaire Go statique qui combine un trafic réaliste, une vérité terrain datée par oracle noyau et une vérification indépendante par double canal. Chaque outil qui le compose a été comparé selon les six critères et retenu pour sa capacité à satisfaire le déterminisme, le fonctionnement hors ligne et la vérifiabilité.` },
  { p: `Les fondements théoriques mobilisés par l'instrument ont été exposés dans l'ordre où ils interviennent dans le protocole de mesure : d'abord la physique de la congestion et du bufferbloat, puis les mécanismes de contrôle (AQM, contrôle de congestion), ensuite les outils de détection et d'estimation, enfin les métriques et les tests statistiques qui permettent de quantifier les résultats. Cet ordre correspond au flux des expériences : E1 détecte, E2 estime, E3 atténue.` },
  { p: `Les outils étant choisis et la théorie posée, la partie suivante décrit la mise en œuvre proprement dite : installation et protocole expérimental, exécution des campagnes E1, E2 et E3, présentation des résultats obtenus, discussion et limites.` },
];
