// 07-refs — Références bibliographiques et webographiques LIEN.
module.exports = [
  { h0: `RÉFÉRENCES BIBLIOGRAPHIQUES` },
  { refs: [
    `[1] HØILAND-JØRGENSEN T., McKENNEY P., TAILLET D., GETTYS J., ERICKSEN E., 2018. The Flow Queue CoDel Packet Scheduler and Active Queue Management. Request for Comments 8290, IETF.`,
    `[2] NICHOLS K., JACOBSON V., 2012. Controlling Queue Delay. ACM Queue, vol. 10, n° 5.`,
    `[3] GETTYS J., NICHOLS K., 2011. Bufferbloat : Dark Buffers in the Internet. ACM Queue, vol. 9, n° 11 ; Communications of the ACM, vol. 55, n° 1, 2012.`,
    `[4] CARDWELL N., CHENG Y., GUNAWARDENA C., YEGANEH S., 2016. BBR : Congestion-Based Congestion Control. ACM Queue, vol. 14, n° 5.`,
    `[5] HA S., RHEE I., XU L., 2008. CUBIC : A New TCP-Friendly High-Speed TCP Variant. ACM SIGOPS Operating Systems Review, vol. 42, n° 5.`,
    `[6] RHEE I., XU L., 2018. CUBIC for Fast and Long Distance Networks. Request for Comments 8312, IETF.`,
    `[7] HØILAND-JØRGENSEN T., 2018. Piece of CAKE : A Comprehensive Queue Management Solution for Home Gateways. arXiv preprint arXiv:1804.10007.`,
    `[8] ITU-T, 2019. Recommandation G.107 : The E-model, a Computational Model for Use in Transmission Planning. Union Internationale des Télécommunications.`,
    `[9] JIANG H., et al., 2010. Taming the Tigers : Understanding and Mitigating the Impact of Bufferbloat in Satellite Networks. Proceedings of ACM IMC 2010.`,
    `[10] NIST, 2015. FIPS 180-4 : Secure Hash Standard (SHA-256). National Institute of Standards and Technology.`,
    `[11] GETTYS J., 2011. ISP Colloquium on Bufferbloat. IETF 80, Prague.`,
  ] },

  { h0: `RÉFÉRENCES WEBOGRAPHIQUES` },
  { refs: [
    `[12] https://www.yas.mg/particulier/forfaits-mobiles/internet/, Forfaits internet prépayés Yas, consulté le 31/08/2026.`,
    `[13] https://www.yas.mg/particulier/internet-fixe/fibre/, Fibre optique Yas, consulté le 31/08/2026.`,
    `[14] https://www.yas.mg/entreprise/large-business/internet-et-connectivite/, Offres entreprise Yas, consulté le 31/08/2026.`,
    `[15] https://www.orange.mg/fr/akama-et-be-connect.html, Forfaits Orange Akama et Be Connect, consulté le 31/08/2026.`,
    `[16] https://blog.sahazamarline.com/2024/03/tarifs-des-forfaits-internet-airtel.html, Tarifs des forfaits internet Airtel, 16/03/2024, consulté le 31/08/2026.`,
    `[17] https://newsmada.com/2025/10/24/internet-mobile-lartec-interpelle-les-operateurs-sur-les-tarifs/, L'ARTEC interpelle les opérateurs sur les tarifs, newsmada.com, 24/10/2025.`,
    `[18] https://www.lexpress.mg/2025/11/prix-de-linternet-bras-de-fer-entre-le.html, Prix de l'internet : bras de fer entre l'État et les opérateurs, L'Express de Madagascar, 26/11/2025.`,
    `[19] https://www.cable.co.uk/mobiles/worldwide-data-pricing/, Worldwide Mobile Data Pricing 2024, Cable.co.uk, données 2023.`,
    `[20] https://www.moov.mg/actualite/103006-starlink-a-madagascar-des-nouveaux-tarifs-font-debat, Starlink à Madagascar : des nouveaux tarifs font débat, moov.mg, 19/06/2025.`,
    `[21] https://starlink.com/mg/residential, Starlink Madagascar, offre Résidentiel, consulté en 2026.`,
    `[22] https://www.artec.mg/, Autorité de Régulation des Technologies de Communication, consulté en 2026.`,
    `[23] https://www.meteomadagascar.mg/, Météo Madagascar, Direction Générale de la Météorologie, consulté en 2026.`,
    `[24] https://man7.org/linux/man-pages/man8/tc-netem.8.html, tc-netem(8), manual Linux.`,
    `[25] https://man7.org/linux/man-pages/man8/tc.8.html, tc(8), manual Linux.`,
    `[26] https://man7.org/linux/man-pages/man8/ip-netns.8.html, ip-netns(8), manual Linux.`,
    `[27] https://flent.org, Flent : The FLExible Network Tester, consulté en 2026.`,
    `[28] https://iperf.fr, iperf3, consulté en 2026.`,
    `[29] https://go.dev, The Go Programming Language, consulté en 2026.`,
    `[30] https://releases.ubuntu.com/24.04/, Ubuntu 24.04 LTS, consulté en 2026.`,
  ] },
];
