// Références bibliographiques et webographiques (reprises verbatim du draft).
module.exports = [
  { h0: 'RÉFÉRENCES BIBLIOGRAPHIQUES' },
  { pNoIndent: 'Auteurs, Éditeur, année d\'édition. Titre de l\'ouvrage ou de l\'article.' },
  { refs: [
    `[30] IETF, 2017. RFC 8290  The Flow Queue CoDel Packet Scheduler and Active Queue Management.`,
    `[31] IETF, 2017. RFC 8289  Controlled Delay Active Queue Management.`,
    `[32] IETF, 2015. RFC 7567  IETF Recommendations Regarding Active Queue Management.`,
    `[33] NICHOLS K., JACOBSON V., ACM Queue, 2011. Controlling Queue Delay.`,
    `[34] GETTYS J., NICHOLS K., ACM Queue, 2011. Bufferbloat  Dark Buffers in the Internet.`,
    `[35] CARDWELL N. et al., ACM Queue, 2016. BBR  Congestion-Based Congestion Control.`,
    `[36] HA S., RHEE I., XU L., ACM SIGOPS Operating Systems Review, 2008. CUBIC  A New TCP-Friendly High-Speed TCP Variant.`,
    `[37] IETF, 2018. RFC 8312  CUBIC for Fast Long-Distance Networks.`,
    `[38] HØILAND-JØRGENSEN T. et al., arXiv, 2018. Piece of CAKE  A Comprehensive Queue Management Solution for Home Gateways.`,
    `[39] MASSEY F. J., Journal of the American Statistical Association, 1951. The Kolmogorov-Smirnov Test for Goodness of Fit.`,
    `[40] KESHAV S., ACM SIGCOMM, 1991. A Control-Theoretic Approach to Flow Control.`,
    `[41] JAIN M., DOVROLIS C., Passive and Active Measurement, 2002. Pathload  A Measurement Tool for End-to-End Available Bandwidth.`,
    `[42] ITU-T, 2019. Recommandation G.107  The E-model, a computational model for use in transmission planning.`,
    `[43] HØILAND-JØRGENSEN T., 2017. Flent  The FLExible Network Tester.`,
    `[45] BLAND J. M., ALTMAN D. G., The Lancet, 1986. Statistical methods for assessing agreement between two methods of clinical measurement.`,
    `[46] République de Madagascar, 2010. Arrêté n° 04.1492010-MESupReS relatif aux grades, titres et diplômes nationaux dans le système LMD.`,
    `[47] République de Madagascar, 2008. Décret n° 2008-179 portant réforme du système d'enseignement supérieur et de recherche (LMD).`,
    `[76] NIST, 2015. FIPS 180-4  Secure Hash Standard (SHA-256).`,
  ] },

  { h0: 'RÉFÉRENCES WEBOGRAPHIQUES' },
  { pNoIndent: 'Adresse URL, Titre du document, date de consultation.' },
  { refs: [
    `[1] httpsdatareportal.comreportsdigital-2026-madagascar, Digital 2026  Madagascar, juillet 2026.`,
    `[2] httpstradingeconomics.commadagascarindividuals-using-the-internet-percent-of-population-wb-data.html, Individuals using the Internet (% of population), Banque Mondiale, juillet 2026.`,
    `[3] httpsdatareportal.comdigital-in-madagascar, Digital in Madagascar, juillet 2026.`,
    `[4] httpswww.speedtest.netglobal-indexmadagascar, Speedtest Global Index  Madagascar, Ookla, juillet 2026.`,
    `[5] httpswww.agenceecofin.comactualites-numerique0707-139956-madagascar-les-deputes-appellent-a-l-extension-de-la-couverture-telecoms, Couverture 4G à Madagascar, Agence Ecofin  UIT, juillet 2026.`,
    `[6] httpsfr.wikipedia.orgwikiMETISS, METISS, juillet 2026.`,
    `[7] httpsceb.mufilesfilesCommuniqueMISE%20EN%20SERVICE%20DU%20CABLE%20METISS.pdf, Mise en service du câble METISS, CEB Maurice, juillet 2026.`,
    `[8] httpswww.madagascarnewsroom.com202412madagascar-cables-sous-marins--t4.html, Câbles sous-marins à Madagascar, juillet 2026.`,
    `[9] httpswww.connectingafrica.comconnectivity2africa-reaches-the-shores-of-madagascar, 2Africa reaches the shores of Madagascar, juillet 2026.`,
    `[10] httpswww.axian-telecom.comcirdowee202302AXIAN-Telecom-Press-release-2Africa-landing-in-Madagascar-VA.pdf, Atterrissement 2Africa à Mahajanga, Axian Telecom, juillet 2026.`,
    `[11] httpsstarlink.commgresidential, Starlink Madagascar  offre Résidentiel, juillet 2026.`,
    `[12] httpswww.connectingafrica.combroadbandstarlink-beams-into-madagascar, Starlink beams into Madagascar, juillet 2026.`,
    `[13] httpsstarlink.commgservice-plans, Starlink Madagascar  forfaits, juillet 2026.`,
    `[14] httpswww.moov.mgactualite103006-starlink-a-madagascar-des-nouveaux-tarifs-font-debat, Tarifs Starlink à Madagascar, juillet 2026.`,
    `[15] https2424.mginternet-starlink-lance-un-forfait-a-136-000-ariary-avec-le-kit-mini-dish, Forfait Starlink et kit mini dish, juillet 2026.`,
    `[16] httpswww.jirama.mgcommuniques, Communiqués et prévisions de coupures, JIRAMA, juillet 2026.`,
    `[17] httpswww.rfi.frfrafrique20250610-madagascar-a-antananarivo-lassitude-et-debrouillardise-de-commercants-face-aux-delestages, Délestages à Antananarivo, RFI, juillet 2026.`,
    `[18] httpswww.lexpress.mg202506electricite-la-jirama-annonce-une.html, Intensification du délestage, L'Express de Madagascar, juillet 2026.`,
    `[19] httpswww.studiosifaka.orgarticlesactualitesitem8161-banque-mondiale-madagascar-face-a-un-risque-de-coupure-d-electricite-accrue-en-2025-et-2026.html, Risque de coupures accru 2025-2026, Banque Mondiale, juillet 2026.`,
    `[20] httpswww.artec.mgartec-madagascar-regulation-telecoms-et-tic-a-propos, À propos de l'ARTEC, juillet 2026.`,
    `[21] httpswww.artec.mgobservatoirechiffre.php, Observatoire du marché, ARTEC, juillet 2026.`,
    `[22] httpswww.artec.mgobservatoireinfrastructure.php, Observatoire des infrastructures, ARTEC, juillet 2026.`,
    `[23] httpswww.fratel.orgdocuments201906questionnaire-FRATEL-couverture-et-QoS-mobile-ARTEC-Madagascar.pdf, Questionnaire couverture et QoS mobile, FRATEL  ARTEC, juillet 2026.`,
    `[24] httpswww.artec.mgmateriels-et-revendeurs-agrees, Matériels homologués et revendeurs agréés, ARTEC, juillet 2026.`,
    `[25] httpscertibridge.mgservicesrf-homologation-servicesartec, Homologation RF ARTEC, juillet 2026.`,
    `[26] République de Madagascar, 2015. Loi n° 2014-038 du 9 janvier 2015 sur la protection des données à caractère personnel.`,
    `[27] httpswww.dlapiperdataprotection.comindex.htmlt=law&c=MG, Data protection laws in Madagascar, DLA Piper, juillet 2026.`,
    `[28] httpswww.pic.commerce.mgfrautorite-de-regulation-des-technologies-de-communication-artec, Missions de l'ARTEC, juillet 2026.`,
    `[44] httpsflent.org, Flent  The FLExible Network Tester, juillet 2026.`,
    `[48] httpsiperf.fr, iperf3, juillet 2026.`,
    `[49] httpsman7.orglinuxman-pagesman8tc-netem.8.html, tc-netem(8), juillet 2026.`,
    `[50] httpsman7.orglinuxman-pagesman8tc.8.html, tc(8), juillet 2026.`,
    `[51] httpsman7.orglinuxman-pagesman8ip-netns.8.html, ip-netns(8), juillet 2026.`,
    `[52] httpswww.tcpdump.org, tcpdump  libpcap, juillet 2026.`,
    `[53] httpszenodo.org, Zenodo, juillet 2026.`,
    `[54] httpsreleases.ubuntu.com24.04, Ubuntu 24.04 LTS, juillet 2026.`,
    `[55] httpsgo.dev, Le langage Go, juillet 2026.`,
    `[57] httpswww.bufferbloat.net, Bufferbloat.net, juillet 2026.`,
    `[58] httpswww.wireshark.org, Wireshark, juillet 2026.`,
    `[59] httpmahimahi.mit.edu, mahimahi, juillet 2026.`,
    `[60] httpswww.nsnam.org, ns-3, juillet 2026.`,
    `[61] httpswww.r-project.org, R, juillet 2026.`,
    `[62] httpsscipy.org, SciPy, juillet 2026.`,
    `[63] httpsgithub.comgonumplot, gonumplot, juillet 2026.`,
    `[64] httpsgithub.comajstarkssvgo, svgo, juillet 2026.`,
    `[65] httpsmatplotlib.org, matplotlib, juillet 2026.`,
    `[66] httpsobservablehq.complot, Observable Plot, juillet 2026.`,
    `[67] httpsvega.github.iovega-lite, Vega-Lite, juillet 2026.`,
    `[68] httpsxtermjs.org, xterm.js, juillet 2026.`,
    `[69] httpspkg.go.devembed, goembed, juillet 2026.`,
    `[70] httpsgrafana.com, Grafana, juillet 2026.`,
    `[71] httpswww.netdata.cloud, netdata, juillet 2026.`,
    `[72] httpswww.zabbix.com, Zabbix, juillet 2026.`,
    `[73] httpswww.nagios.org, Nagios, juillet 2026.`,
    `[74] httpsgithub.comiputilsiputils, iputils (ping), juillet 2026.`,
    `[75] httpwww.hping.org, hping, juillet 2026.`,
    `[77] httpsman7.orglinuxman-pagesman8ip-route.8.html, ip-route(8), juillet 2026.`,
    `[78] httpsman7.orglinuxman-pagesman1taskset.1.html, taskset(1), juillet 2026.`,
    `[79] httpsman7.orglinuxman-pagesman7socket.7.html, socket(7), juillet 2026.`,
    `[80] httpswww.gnu.orgsoftwaremake, GNU Make, juillet 2026.`,
    `[81] httpsgit-scm.com, git, juillet 2026.`,
  ] },
];
