// Annexes A, B, C (reprises du draft, structurées).
module.exports = [
  { h0: `ANNEXES` },

  { h2annex: `Annexe A. Commandes de l'instrument` },
  { p: `Le cycle de vie complet de l'instrument est piloté par GNU Make [80]. Le {tabRef:annexeCmd} recense les commandes disponibles, de la construction du binaire à la régénération des figures depuis les données gelées.` },
  { table: {
      id: 'annexeCmd',
      caption: `Commandes Makefile de l'instrument CGO.`,
      header: ['Commande', 'Description'],
      rows: [
        ['make build', 'construction du binaire statique'],
        ['make test', 'suite de tests unitaires'],
        ['make test-linux', 'suite de tests spécifique Linux (netlink, qdisc)'],
        ['make figures', 'régénération de toutes les figures depuis les CSV gelés'],
        ['make demo-up', 'démonstration locale avec interface web'],
        ['make verify', 'réconciliation double canal (oracle vs ping)'],
        ['make negctl', 'contrôles négatifs NC-1, NC-2, NC-3 (doivent échouer)'],
        ['make preregister', 'versement du pré-enregistrement horodaté'],
        ['make offline-kit', 'export du kit hors ligne pour soutenance'],
        ['make disk-check', 'vérification de l\u2019enveloppe de stockage (~8 Go)'],
        ['make rescore', 're-pointage déterministe de tous les détecteurs'],
        ['make sweep', 'optimisation paramétrique par balayage systématique'],
      ],
      widths: [30, 70],
  } },
  { p: `Le binaire accepte les options suivantes : --e1 (expérience E1), --e3 (expérience E3), --sweep (balayage paramétrique), --serve (serveur HTTP embarqué), --dry-run (simulation sans action), --negctl (contrôles négatifs), --preregister (pré-enregistrement), --reallink (bras 4G réel) et --demo (démonstration locale).` },
  { p: `L'épinglage CPU est assuré par le script deploy/taskset.sh : le processeur 0 est dédié au flux de données, au sondeur et au rejoueur ; le processeur 1 est dédié à ping, iperf3, tcpdump et au pointage. Cet épinglage garantit que les processus de mesure ne perturbent pas la génération de trafic.` },

  { h2annex: `Annexe B. Schémas de données complets` },
  { p: `Le fichier e1onsets.csv contient les colonnes suivantes : onsetid (identifiant unique), family (échelon, rampe, effondrement), context (contexte réseau), profile (profil de lien), netemrttms (RTT configuré par netem), scheduledts (horodatage programmé), ratebeforembps (débit avant événement), rateaftermbps (débit après événement), ramps (pente de la rampe), detector (nom du détecteur), channel (ping5hz ou tcpinfo1hz), rawlagms (délai brut mesuré), confirmedlagms (délai confirmé par oracle), falsepositive (booléen), missed (booléen), confirmsamples (nombre d'échantillons confirmés), seed (graine aléatoire).` },
  { p: `Le fichier e3events.csv contient les colonnes historiques gelées (nombre vérifié au démarrage) auxquelles s'ajoutent : arm (bras de configuration), linkprofile (profil de lien), cc (contrôle de congestion), qdims (QDI en millisecondes), ttbbacklogms (TTB en millisecondes), voipjitterms (gigue VoIP), voiplosspct (taux de perte VoIP), wastedbytes (octets gaspillés en retransmissions), costarperh (coût par heure en ariary), cpuusagepct (utilisation CPU). Le champ CompositeScore est gelé à 0 ; le LFI est une métrique secondaire rapportée avec ses effectifs.` },
  { p: `La table de réconciliation associe à chaque grandeur (RTT, débit, perte) : le canal A (pipeline interne), le canal B (instrument tiers : ping -D, iperf3), l'écart absolu, l'écart relatif, le seuil de tolérance et le verdict (conforme, suspect ou échec).` },
  { p: `Le journal des décisions (pkg/api/decision_log.go) enregistre pour chaque action : timestamp (horodatage Unix), condition (métrique déclencheuse), discipline (qdisc appliqué), target_ms (cible en millisecondes), reason (raison textuelle), confidence (confiance entre 0 et 1), applied (booléen), revoked (booléen), rttms (RTT mesuré), lossrate (taux d'abandon), LFI (équité), bufferbloat (booléen), recovery_sec (secondes de récupération) et le taux d'utilisation du débit en pourcentage.` },
  { p: `La configuration de l'API est générée et appliquée par deux modules : pkg/api/config_gen.go produit la configuration par défaut via GET /api/v1/config/default, et pkg/api/apply.go applique une configuration validée via POST /api/v1/config/apply. La validation (pkg/config/validation.go) vérifie les types, les plages, les champs requis et les dépendances croisées avant toute application.` },

  { h2annex: `Annexe C. Registre des risques` },
  { p: `Le {tabRef:annexeRisques} présente le registre des risques constitué avant les campagnes, avec la probabilité, l'impact et l'atténuation prévue pour chacun.` },
  { table: {
      id: 'annexeRisques',
      caption: `Registre des risques et mitigations.`,
      header: ['Risque', 'Probabilité', 'Impact', 'Atténuation'],
      rows: [
        ['KS manque la marge de 2 s sur les rampes', 'Moyenne', 'Moyen', 'Résultat négatif pré-enregistré, frontière rapportée'],
        ['Instabilité du réglage de débit netlink à 10 Hz', 'Moyenne', 'Élevé', 'Trempage de 30 minutes, rejoueur Go pur en solution principale'],
        ['Bruit de la machine virtuelle', 'Moyenne', 'Moyen', 'Épinglage CPU, covariable processeur, plans appariés'],
        ['Bras 4G réel bloqué', 'Faible à moyenne', 'Moyen', 'Abandon pour cause documentée uniquement, acquisition en semaine 1'],
        ['Dérive du périmètre fonctionnel', 'Élevée', 'Élevé', 'Exclu par conception, adaptation par règles uniquement'],
        ['Interruption nocturne (délestage JIRAMA)', 'Moyenne', 'Moyen', 'Points de contrôle par événement, reprise, journalisation'],
        ['Dérive des chiffres cités dans les sources web', 'Faible', 'Faible', 'Citations avec date de consultation, pages sauvegardées'],
        ['Dépassement de stockage disque', 'Faible', 'Élevé', 'Captures fenêtrées, échantillon d\u2019audit, ~8 Go prévus au total'],
        ['Détecteur gradient faux positifs sur gigue normale', 'Moyenne', 'Moyen', 'Fenêtre N = 10 échantillons, calibration sur phases dédiées'],
        ['EWMA retard de détection sur rampes lentes', 'Moyenne', 'Moyen', 'Alpha ajustable (0,125 par défaut), comparé au KS comme alternative'],
      ],
      widths: [32, 14, 12, 42],
  } },

  { h2annex: `Annexe D. Présentation de l'Université d'Antananarivo` },
  { p: `Le présent mémoire est soutenu dans le cadre de la Mention Informatique de l'Université d'Antananarivo, établissement au sein duquel l'auteur a suivi sa formation. Cette annexe présente brièvement l'établissement de rattachement académique, en complément de la présentation de l'organisme d'accueil du stage développée dans la première partie.` },
  { p: `L'Université d'Antananarivo est la plus ancienne et la plus importante des universités publiques de Madagascar. Fondée en 1961, peu après l'indépendance, elle est située dans la capitale, principalement sur le campus d'Ankatso, et accueille plusieurs dizaines de milliers d'étudiants. Elle est organisée en domaines de formation et en établissements (facultés, écoles et instituts) couvrant les sciences et technologies, les sciences humaines et sociales, le droit, l'économie, la gestion, la médecine et les lettres. Depuis la mise en œuvre du système Licence-Master-Doctorat (LMD), la formation est structurée en domaines, mentions et parcours.` },
  { p: `La formation à l'origine de ce mémoire relève du Domaine Sciences et Technologies, Mention Informatique. Cette mention forme, aux grades de Licence, de Master et de Doctorat, des spécialistes de la conception, du développement et de l'administration des systèmes informatiques et des réseaux. Le cursus de Master, sanctionné par la rédaction et la soutenance d'un mémoire de fin d'études, associe enseignements théoriques (algorithmique, réseaux, systèmes, bases de données, génie logiciel, sécurité) et travail de recherche appliquée. Le mémoire de fin d'études, souvent adossé à un stage en entreprise ou en institution, vise à démontrer la capacité de l'étudiant à poser une problématique, à mobiliser l'état de l'art, à concevoir une solution et à en évaluer rigoureusement les résultats.` },
  { p: `Le {tabRef:univ} rassemble les principaux éléments d'identification de l'établissement de rattachement académique.` },
  { table: {
      id: 'univ',
      caption: `Fiche d'identification de l'établissement de rattachement académique.`,
      header: ['Rubrique', 'Renseignement'],
      rows: [
        ['Établissement', 'Université d’Antananarivo'],
        ['Statut', 'Université publique'],
        ['Année de fondation', '1961'],
        ['Localisation', 'Antananarivo (campus d’Ankatso), Madagascar'],
        ['Domaine', 'Sciences et Technologies'],
        ['Mention', 'Informatique'],
        ['Diplôme préparé', 'Master en Informatique (système LMD)'],
      ],
      widths: [30, 70],
  } },
];
