// 09-annexes — Annexes LIEN : schéma CSV, portes, guide, présentation université.
module.exports = [
  { h0: `ANNEXES` },

  { h2annex: `Annexe A. Schéma du fichier aqm_eval.csv` },
  { p: `Chaque événement franchissant les portes est gelé dans une archive par run, sous la forme d'un fichier aqm_eval.csv dont chaque ligne décrit un événement. Le {tabRef:csvSchema} détaille les colonnes dans leur ordre d'écriture.` },
  { table: {
      id: 'csvSchema',
      caption: `Colonnes du fichier aqm_eval.csv`,
      header: [`Colonne`, `Signification`],
      rows: [
        [`run_id`, `identifiant du run, horodatage de création`],
        [`event_id`, `numéro d'ordre de l'événement dans le run`],
        [`profile`, `profil de lien testé (P1 à P4)`],
        [`qdisc`, `discipline de file appliquée (pfifo_fast, fq_codel, cake)`],
        [`cc`, `contrôle de congestion du flux de charge (cubic, bbr)`],
        [`direction`, `sens de charge gelé avec la ligne : up (montée, défaut historique) ou down (descente) ; scinde les groupes d'analyse`],
        [`repetition`, `numéro de répétition de la cellule`],
        [`rtt_p50_ms`, `médiane du temps d'aller-retour sur la fenêtre de charge`],
        [`rtt_p95_ms`, `95e percentile du temps d'aller-retour sur la fenêtre de charge`],
        [`qdi_ms`, `écart p95 moins médiane de la latence, en millisecondes`],
        [`voip_r`, `score R du model E calculé depuis les conditions mesurées (vide pour les runs antérieurs à l'implémentation)`],
        [`jfi_pct`, `indice d'équité de Jain inter-flux, 0 à 100 (0 pour le flux unique, où l'équité ne se mesure pas)`],
        [`small_p95_ms`, `95e percentile des complétions des sondes critiques`],
        [`deadline_ok_pct`, `taux de complétions sous l'échéance choisie, en pourcentage`],
        [`bulk_goodput_mbps`, `débit utile du flux de charge, en mégabits par seconde`],
        [`drops`, `paquets écartés par la discipline de file pendant l'événement`],
        [`retransmissions`, `segments TCP retransmis`],
        [`wasted_bytes`, `octets retransmis, base du calcul de coût`],
        [`cost_ar_per_h`, `coût horaire du gaspillage en ariary, au palier tarifaire actif (POST /api/cost/tier, défaut yas-month-4.5gb)`],
        [`cpu_pct`, `utilisation processeur moyenne, surveillée par la porte G7`],
        [`rtt_base_p50_ms`, `médiane de la latence au repos, référence de la note bufferbloat (vide pour les runs antérieurs)`],
        [`rtt_base_p95_ms`, `95e percentile de la latence au repos, référence de la note bufferbloat (vide pour les runs antérieurs)`],
        [`gate_status`, `verdict des portes : valid, degraded ou invalid (quarantaine)`],
      ],
      widths: [24, 76],
  } },
  { p: `Le manifeste du run accompagne ce fichier : il enregistre l'empreinte SHA-256 de chaque fichier gelé, et la commande verify les recalcule à la demande. Le premier run qui a suivi l'implémentation du score de voix laisse la colonne voip_r vide pour les vagues antérieures : le score est calculé depuis, et les archives l'ont précédé.` },

  { h2annex: `Annexe B. Les huit portes de qualité, conditions exactes` },
  { p: `Le {tabRef:portesAnnexe} reprend les huit portes avec leurs conditions d'évaluation exactes, telles qu'implémentées dans le moteur de campagne.` },
  { table: {
      id: 'portesAnnexe',
      caption: `Portes de qualité : condition et statut consécutif`,
      header: [`Porte`, `Condition`, `Échec`],
      rows: [
        [`G0`, `La cible répond aux pings de la fenêtre de repos`, `invalid`],
        [`G1`, `Le flux de masse a transmis des octets`, `invalid`],
        [`G2`, `Les sondes produisent des valeurs pendant la charge`, `degraded`],
        [`G3`, `Latence plausible : p95 sous dix fois le délai du profil plus 200 ms`, `invalid`],
        [`G4`, `Débit cohérent avec la capacité du sens mesuré : montante, entre la moitié et 1,1 fois CapUp ; descendante, plancher 1 % de CapDown (tuyau mort seul, le verdict download se jouant sur la latence)`, `invalid`],
        [`G5`, `Aucune ligne (run, événement) dupliquée au gel`, `invalid`],
        [`G6`, `Baseline stable : p95 moins médiane du repos sous le plus grand de 5 ms et 20 % de la médiane`, `degraded`],
        [`G7`, `Processeur non saturé : moyenne sous 90 %`, `invalid`],
      ],
      widths: [10, 70, 20],
  } },
  { p: `Un événement dont toute porte majeure échoue est marqué invalid et part en quarantaine : sa ligne est écrite, comptée et exclue des médianes (les lignes degraded restent exploitables). Les archives en comptent 214 pour 136 lignes valides, ratio assumé et publié, qui décrit aussi honnêtement la difficulté de tenir un banc stable qu'il filtre les événements exploitables.` },

  { h2annex: `Annexe C. Guide de démarrage de l'instrument` },
  { p: `L'instrument se présente comme un binaire unique. Sur un poste Linux, la commande cgo setup conduit l'installation guidée en sept étapes idempotentes : détection des dépendances, installation de ce qui manque, construction du frontend puis du binaire, choix du mode d'exécution, configuration du banc, entrées de résolution locale, vérification finale. La commande cgo --serve démarre le tableau de bord web et l'API sur le port 9090 ; cgo tui ouvre le tableau de bord terminal ; cgo run --profiles P2 --reps 1 exécute une campagne complète avec gel et résumé ; cgo audit mesure le lien réel accessible depuis le poste ; cgo verify recalcule les empreintes du gel ; cgo figures régénère les figures depuis les archives.` },
  { p: `Le moteur de déploiement, cgo kit, expose dix-huit actions couvrant le cycle de vie de toute machine du banc, virtuelle ou physique : doctor (diagnostic), scan (découverte), ensure (garantie de présence et d'état), align, build, deploy, bootstrap, status, logs, health (état du tableau de bord), tunnel, snapshot (instantané avant opération risquée, hyperviseur requis), snapshots (liste des instantanés), revert (retour à l'instantané), ssh, ps, backup (rappel des archives) et verify (empreintes recalculées sur la machine distante). Les sauvegardes protègent toute expérimentation : un banc se casse, l'état sain se restaure en une commande.` },

  { h2annex: `Annexe D. [[PRÉSENTATION DE L'ÉTABLISSEMENT DE RATTACHEMENT ACADÉMIQUE]]` },
  { p: `[[RÉDIGER ICI la présentation de l'établissement de rattachement : dénomination officielle, statut, année de fondation, localisation, organisation en domaines, mentions et parcours, formation concernée et diplôme préparé. Terminer par la fiche d'identification ci-dessous, dûment complétée.]]` },
  { table: {
      id: 'univ',
      caption: `Fiche d'identification de l'établissement de rattachement académique`,
      header: [`Rubrique`, `Renseignement`],
      rows: [
        [`Établissement`, `[[DÉNOMINATION OFFICIELLE]]`],
        [`Statut`, `[[STATUT — PUBLIC / PRIVÉ]]`],
        [`Année de fondation`, `[[ANNÉE]]`],
        [`Localisation`, `[[VILLE (CAMPUS), PAYS]]`],
        [`Domaine`, `[[DOMAINE]]`],
        [`Mention`, `[[MENTION]]`],
        [`Diplôme préparé`, `[[DIPLÔME (SYSTÈME LMD)]]`],
      ],
      widths: [30, 70],
  } },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },
  { pNoIndent: ' ' },

  { h2annex: `Annexe E. Captures du tableau de bord` },
  { p: `Les trois captures de cette annexe montrent l'interface de supervision telle qu'elle s'est présentée pendant les campagnes, à une définition de 1920 par 1080 pixels. Les données affichées proviennent du service en cours d'exécution au moment de la capture ; les valeurs y sont celles du serveur de mesure, aucune n'est produite par le navigateur.` },
  { fig: { id: 'shotCampagne', file: 'shot-campagne', screenshot: true, caption: `Vue Campagne : profils, répétitions, échéance, cible, armement à double confirmation` } },
  { p: `La {figRef:shotCampagne} montre le pilotage : la sélection des profils et des répétitions, l'échéance et la cible, le récapitulatif de la matrice, et l'armement à double confirmation avant tout démarrage. Aucun réglage ne s'applique avant confirmation, et l'écran affiche toujours ce qui sera exécuté.` },
  { fig: { id: 'shotLive', file: 'shot-live', screenshot: true, caption: `Vue Live : cartes de latence et de débit, comparaison avec la référence, journal des événements` } },
  { p: `La {figRef:shotLive} montre la mesure en cours : cartes de latence et de débit, mur de comparaison entre la référence gelée et la configuration appliquée, journal des événements récents. La progression de l'événement courant sur le total de la matrice reste visible en permanence, de même que les paquets écartés par la discipline.` },
  { fig: { id: 'shotResultats', file: 'shot-resultats', screenshot: true, caption: `Vue Résultats : classement des cellules, épinglage de deux lignes, interprétation calculée` } },
  { p: `La {figRef:shotResultats} montre la lecture après campagne : le classement des cellules gelées par critère, l'épinglage de deux lignes pour comparaison, et l'interprétation calculée qui accompagne chaque cellule, verdict en mots et prescription de configuration prête à copier.` },
];
