// 09-annexes — Annexes LIEN : schéma CSV, portes, guide, présentation université.
module.exports = [
  { h0: `ANNEXES` },

  { h2annex: `Annexe A. Schéma du fichier aqm_eval.csv` },
  { p: `Chaque événement franchissant les portes est gelé dans une archive par run, sous la forme d'un fichier aqm_eval.csv dont chaque ligne décrit un événement. Le {tabRef:csvSchema} détaille les colonnes dans leur ordre d'écriture.` },
  { table: {
      id: 'csvSchema',
      caption: `Colonnes du fichier aqm_eval.csv`,
      header: [`Colonne`, `Signification`],
      rows: [
        [`run_id`, `identifiant du run, horodatage de création`],
        [`event_id`, `numéro d'ordre de l'événement dans le run`],
        [`profile`, `profil de lien testé (P1 à P4)`],
        [`qdisc`, `discipline de file appliquée (pfifo_fast, fq_codel, cake)`],
        [`cc`, `contrôle de congestion du flux de charge (cubic, bbr)`],
        [`repetition`, `numéro de répétition de la cellule`],
        [`rtt_p50_ms`, `médiane du temps d'aller-retour sur la fenêtre de charge`],
        [`rtt_p95_ms`, `95e percentile du temps d'aller-retour sur la fenêtre de charge`],
        [`qdi_ms`, `écart p95 moins médiane de la latence, en millisecondes`],
        [`voip_r`, `score R du model E calculé depuis les conditions mesurées (vide pour les runs antérieurs à l'implémentation)`],
        [`small_p95_ms`, `95e percentile des complétions des sondes critiques`],
        [`deadline_ok_pct`, `taux de complétions sous l'échéance choisie, en pourcentage`],
        [`bulk_goodput_mbps`, `débit utile du flux de charge, en mégabits par seconde`],
        [`drops`, `paquets écartés par la discipline de file pendant l'événement`],
        [`retransmissions`, `segments TCP retransmis`],
        [`wasted_bytes`, `octets retransmis, base du calcul de coût`],
        [`cost_ar_per_h`, `coût horaire du gaspillage en ariary, au palier par défaut`],
        [`cpu_pct`, `utilisation processeur moyenne, surveillée par la porte G7`],
        [`gate_status`, `verdict des portes : valid, degraded ou quarantined`],
      ],
      widths: [24, 76],
  } },
  { p: `Le manifeste du run accompagne ce fichier : il enregistre l'empreinte SHA-256 de chaque fichier gelé, et la commande verify les recalcule à la demande. Le premier run qui a suivi l'implémentation du score de voix laisse la colonne voip_r vide pour les vagues antérieures : le score est calculé depuis, et les archives l'ont précédé.` },

  { h2annex: `Annexe B. Les huit portes de qualité, conditions exactes` },
  { p: `Le {tabRef:portesAnnexe} reprend les huit portes avec leurs conditions d'évaluation exactes, telles qu'implémentées dans le moteur de campagne.` },
  { table: {
      id: 'portesAnnexe',
      caption: `Portes de qualité : condition et statut consécutif`,
      header: [`Porte`, `Condition`, `Échec`],
      rows: [
        [`G0`, `La cible répond aux pings de la fenêtre de repos`, `invalid`],
        [`G1`, `Le flux de masse a transmis des octets`, `invalid`],
        [`G2`, `Les sondes produisent des valeurs pendant la charge`, `degraded`],
        [`G3`, `Latence plausible : p95 sous dix fois le délai du profil plus 200 ms`, `invalid`],
        [`G4`, `Débit cohérent : entre la moitié et 1,1 fois la capacité du profil`, `invalid`],
        [`G5`, `Aucune ligne (run, événement) dupliquée au gel`, `invalid`],
        [`G6`, `Baseline stable : p95 moins médiane du repos sous le plus grand de 5 ms et 20 % de la médiane`, `degraded`],
        [`G7`, `Processeur non saturé : moyenne sous 90 %`, `degraded`],
      ],
      widths: [10, 70, 20],
  } },
  { p: `Un événement dont toute porte majeure échoue part en quarantaine : sa ligne est écrite, comptée et exclue du classement. Les archives en comptent 154 pour 83 lignes valides, ratio assumé et publié, qui décrit aussi honnêtement la difficulté de tenir un banc stable qu'il filtre les événements exploitables.` },

  { h2annex: `Annexe C. Guide de démarrage de l'instrument` },
  { p: `L'instrument se présente comme un binaire unique. Sur un poste Linux, la commande cgo setup conduit l'installation guidée en sept étapes idempotentes : détection des dépendances, installation de ce qui manque, construction du frontend puis du binaire, choix du mode d'exécution, configuration du banc, entrées de résolution locale, vérification finale. La commande cgo --serve démarre le tableau de bord web et l'API sur le port 9090 ; cgo tui ouvre le tableau de bord terminal ; cgo run --profiles P2 --reps 1 exécute une campagne complète avec gel et résumé ; cgo audit mesure le lien réel accessible depuis le poste ; cgo verify recalcule les empreintes du gel ; cgo figures régénère les figures depuis les archives.` },
  { p: `Le moteur de déploiement de la machine virtuelle, cgo kit, expose dix-huit actions couvrant le cycle de vie : doctor (diagnostic), scan (découverte), ensure (garantie de présence et d'état), align, build, deploy, bootstrap, status, logs, health (état du tableau de bord), tunnel, snapshot (instantané avant opération risquée), snapshots (liste des instantanés), revert (retour à l'instantané), ssh, ps, backup (rappel des archives) et verify (empreintes recalculées sur la machine distante). Les instantanés protègent toute expérimentation : un banc se casse, l'état sain se restaure en une commande.` },

  { h2annex: `Annexe D. Présentation de l'Université d'Antananarivo` },
  { p: `Le mémoire est soutenu dans le cadre de la Mention Informatique de l'Université d'Antananarivo, plus ancienne et plus importante des universités publiques de Madagascar. Fondée en 1961, peu après l'indépendance, elle est située dans la capitale, principalement sur le campus d'Ankatso, et organisée en domaines, mentions et parcours depuis la mise en œuvre du système Licence-Master-Doctorat. La formation relève du Domaine Sciences et Technologies, Mention Informatique, qui forme aux grades de Licence, de Master et de Doctorat des spécialistes de la conception, du développement et de l'administration des systèmes informatiques et des réseaux.` },
  { p: `Le cursus de Master, sanctionné par la rédaction et la soutenance d'un mémoire de fin d'études, associe enseignements théoriques et travail de recherche appliquée, souvent adossé à un stage en institution. Le mémoire vise à démontrer la capacité de l'étudiant à poser une problématique, à mobiliser l'état de l'art, à concevoir une solution et à en évaluer rigoureusement les résultats. Le {tabRef:univ} rassemble les éléments d'identification de l'établissement de rattachement académique.` },
  { table: {
      id: 'univ',
      caption: `Fiche d'identification de l'établissement de rattachement académique`,
      header: [`Rubrique`, `Renseignement`],
      rows: [
        [`Établissement`, `Université d'Antananarivo`],
        [`Statut`, `Université publique`],
        [`Année de fondation`, `1961`],
        [`Localisation`, `Antananarivo (campus d'Ankatso), Madagascar`],
        [`Domaine`, `Sciences et Technologies`],
        [`Mention`, `Informatique`],
        [`Diplôme préparé`, `Master en Informatique (système LMD)`],
      ],
      widths: [30, 70],
  } },

  { h2annex: `Annexe E. Captures du tableau de bord` },
  { p: `Les trois captures de cette annexe montrent l'interface de supervision telle qu'elle s'est présentée pendant les campagnes, à une définition de 1920 par 1080 pixels. Les données affichées proviennent du service en cours d'exécution au moment de la capture ; les valeurs y sont celles du serveur de mesure, aucune n'est produite par le navigateur.` },
  { fig: { id: 'shotCampagne', file: 'shot-campagne', screenshot: true, caption: `Vue Campagne : profils, répétitions, échéance, cible, armement à double confirmation` } },
  { p: `La {figRef:shotCampagne} montre le pilotage : la sélection des profils et des répétitions, l'échéance et la cible, le récapitulatif de la matrice, et l'armement à double confirmation avant tout démarrage. Aucun réglage ne s'applique avant confirmation, et l'écran affiche toujours ce qui sera exécuté.` },
  { fig: { id: 'shotLive', file: 'shot-live', screenshot: true, caption: `Vue Live : cartes de latence et de débit, comparaison avec la référence, journal des événements` } },
  { p: `La {figRef:shotLive} montre la mesure en cours : cartes de latence et de débit, mur de comparaison entre la référence gelée et la configuration appliquée, journal des événements récents. La progression de l'événement courant sur le total de la matrice reste visible en permanence, de même que les paquets écartés par la discipline.` },
  { fig: { id: 'shotResultats', file: 'shot-resultats', screenshot: true, caption: `Vue Résultats : classement des cellules, épinglage de deux lignes, interprétation calculée` } },
  { p: `La {figRef:shotResultats} montre la lecture après campagne : le classement des cellules gelées par critère, l'épinglage de deux lignes pour comparaison, et l'interprétation calculée qui accompagne chaque cellule, verdict en mots et prescription de configuration prête à copier.` },
];
